### ISSUE TITLE
"Error: Getter not found:" continuously show up

### ISSUE THREAD

**Issue by hoangph271** [fluttercommunity/flutter_launcher_icons#101]
I used pubspec.yaml as following:

```
dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter
```

```
flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/heart.png"
  adaptive_icon_background: #0984e3
  adaptive_icon_foreground: #e84393
```
But these error messages keep showing up, I don't know if there is anymore information I can provide

![Capture](https://user-images.githubusercontent.com/39024711/57838153-5bf1b600-77ee-11e9-885d-adc96bbe23b6.PNG)
