### ISSUE TITLE
andriod icons not replaced

### ISSUE THREAD

**Issue by MitchellQ** [fluttercommunity/flutter_launcher_icons#115]
I am trying to set up launcher icons for my app but I am having trouble getting it to work on andriod 

```
dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
flutter_icons:
  image_path: "assets/peaks.png"
  andoid: "launcher_icon"
  andriod: true
  ios: true
```

result from icons:main
```
Android minSdkVersion = 16
Overwriting default iOS launcher icon with new icon
```

it has generated icons for ios but not andriod and I can't figure out why
