### ISSUE TITLE
flutter_launcher_icon shifting between original flutter icon and custom icon

### ISSUE THREAD

**Issue by Chimba123** [fluttercommunity/flutter_launcher_icons#133]
I am using the package and I have run the command the custom launcher icon is showing but when I open and close the App the launcher icon is shifting between the original flutter icon and the custom icon that is to say it is not persistent

**Comment by adithyaxx** [comment]
I had this issue too but I solved it with the following commands:
```
flutter clean
flutter run --release
```

Just for reference, this is my code in pubspec.yaml:
```
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
```

Hope that helps!
