### ISSUE TITLE
pub get failed

### ISSUE THREAD

**Issue by IC-plus** [fluttercommunity/flutter_launcher_icons#136]
I keep getting pub get failed I not too sure if I set the dependencies correctly 

Error message:
```
flutter packages get
Running "flutter pub get" in App...                      
Because fluttertest depends on both flutter_launcher_icons from hosted and flutter_launcher_icons from path, version solving failed.
pub get failed (1)
exit code 1
```

Dependencies codes:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

  http: ^0.12.0+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons:
    path: assets/images

flutter_icons:
#  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/Logo.png"
  image_path_ios: "assets/images/Logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/py-django.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/py-django.png" # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
```
I tried following this tutorial:
https://www.youtube.com/watch?v=mysyraPhQ5k

**Comment by SimonIT** [comment]
Your config is wrong. Try this:
```yml
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
#  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/Logo.png"
  image_path_ios: "assets/images/Logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/py-django.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/py-django.png" # only available for Android 8.0 devices and above

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
```
