### ISSUE TITLE
Default Icon still showing after install iOS

### ISSUE THREAD

**Issue by daveparks23** [fluttercommunity/flutter_launcher_icons#141]
I still have default icon showing up here and when I swipe the app closed it's the default icon that animates to the home screen.  Everywhere else looks good.
I'm using:
`flutter_launcher_icons: ^0.7.4`
And 
```
flutter_icons:    
  android: "launcher_icon"
  ios: true
  image_path: "assets/tap_tag_app_icon.png"
```
Followed the directions.  I didn't have this problem before but now I do...
Not sure what to look for.
Thanks for any direction.
![IMG_2573](https://user-images.githubusercontent.com/10374129/70190709-4b3a5c00-16bc-11ea-9e3c-cb330a69bdb5.jpg)
