### ISSUE TITLE
Suggestion for doc ?

### ISSUE THREAD

**Issue by EArminjon** [fluttercommunity/flutter_launcher_icons#144]
Hello,

Many of us experiment trouble when using  adaptive_icon_background or adaptive_icon_foreground. Icon or background can be cutted.

So, to prevent that, the simple way is to use a defined size like 1024 / 1024 for all images. And, for the foreground.png, the logo must be centered and not exceed 512 / 512 of the 1024 / 1024.

Example : 

Background.png (1024 / 1024)
![background](https://user-images.githubusercontent.com/37028599/70859617-ff3ab300-1f16-11ea-8851-6f8d78664ba4.png)

Foreground.png,  white logo (512 / 512) on a transparent background (1024 / 1024)
![foreground](https://user-images.githubusercontent.com/37028599/70859618-ff3ab300-1f16-11ea-8c70-0888f617f8c6.png)

Icon.png, both (1024 / 1024)
![icon](https://user-images.githubusercontent.com/37028599/70859619-ff3ab300-1f16-11ea-977a-ca21990f972a.png)

```yaml
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/app/icon.png"
  image_path_android: "assets/app/icon.png"
  adaptive_icon_background: "assets/app/background.png"
  adaptive_icon_foreground: "assets/app/foreground.png"
```
