### ISSUE TITLE
6 unassigned children with iOS

### ISSUE THREAD

**Issue by acoutts** [fluttercommunity/flutter_launcher_icons#153]
```yaml
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
```

```
flutter pub run flutter_launcher_icons:main
```

List of affected icons:
```
Icon-App-50x50@1x.png
Icon-App-50x50@2x.png
Icon-App-57x57@1x.png
Icon-App-57x57@2x.png
Icon-App-72x72@1x.png
Icon-App-72x72@2x.png
```

<img width="664" alt="Screen Shot 2020-01-28 at 6 06 49 AM" src="https://user-images.githubusercontent.com/9597207/73258835-8759dc80-4194-11ea-8d86-b08be4184cb7.png">
