### ISSUE TITLE
Adaptive foreground not working [BUG] Error: The method 'endsWith' was called on null.

### ISSUE THREAD

**Issue by tomasbaran** [fluttercommunity/flutter_launcher_icons#166]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

When I don't use adaptive_icons I don't get any errors. As soon as I use this:
```
  adaptive_icon_background: #000000
  adaptive_icon_foreground: "assets/icons/D.png"
```
I get this error:

```
~/Development/sundee flutter pub get
Running "flutter pub get" in namee...                              0,9s
~/Development/sundee flutter pub run flutter_launcher_icons:main
Android minSdkVersion = 16
Creating default icons Android
Overwriting the default Android launcher icon with a new icon
Creating adaptive icons Android
NoSuchMethodError: The method 'endsWith' was called on null.
Receiver: null
Tried calling: endsWith(".png")
```

### :scroll: Pubspec.yaml

```
name: Namee
description: Desc
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  geolocator: ^5.3.1
  
  flutter_spinkit: ^4.1.2+1
  location_permissions: ^2.0.5
  flutter_launcher_icons: ^0.7.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name: "^0.0.1"
  
flutter_launcher_name:
  name: "Sundee"

flutter_icons:
  image_path: "assets/icons/icon.png"
  ios: true
  android: true
  adaptive_icon_background: #000000
  adaptive_icon_foreground: "assets/icons/D.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 900
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd-Book.ttf
          weight: 400
        - asset: assets/fonts/CircularStd-BookItalic.ttf
          weight: 400
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
