### ISSUE TITLE
[BUG]  requires xml ^3.2.5

### ISSUE THREAD

**Issue by robertoalvesneto** [fluttercommunity/flutter_launcher_icons#178]
Version: `0.7.5`

Because flutter_launcher_icons >=0.7.1 depends on image ^2.1.1 which depends on xml ^3.2.5, flutter_launcher_icons >=0.7.1 requires xml ^3.2.5.
So, because ancoragemCastanhal depends on both xml ^4.1.0 and flutter_launcher_icons 0.7.5, version solving failed.
pub get failed (1; So, because ancoragemCastanhal depends on both xml ^4.1.0 and flutter_launcher_icons 0.7.5, version solving failed.)

     flutter_launcher_icons: "0.7.5"

  flutter_icons:
     android: true
     image_path_android: "img/logo.png"

**Comment by ram231** [comment]
Was planning to upgrade too, I had to temporarily disabled it because the file was already generated,

**Comment by Maxim-Filimonov** [comment]
is there a workaround?

**Comment by ram231** [comment]
Since the `image` version relies on  `<v4.0`(that means it cannot use v4.0 and above). 
you could use my fork here: https://github.com/ram231/flutter_launcher_icons
**Instructions:**
```yaml
# copy this in the dev_dependencies
dev_dependencies:
    flutter_launcher_icons:
    git:
      url: https://github.com/ram231/flutter_launcher_icons.git
```
note that I will discontinue to update the version until the author has updated the dependencies.
