### ISSUE TITLE
[BUG] Background icon missing

### ISSUE THREAD

**Issue by msyagami** [fluttercommunity/flutter_launcher_icons#179]
### :information_source: Info
Version:  v0.7.5
Android Studio: 4.0

### :speech_balloon: Description

The background icon is not displayed, but the foreground one is.
![Screenshot_20200613-184743_One UI Home](https://user-images.githubusercontent.com/53424270/84566847-43253e00-ad29-11ea-8a80-de9628399267.jpg)

### :scroll: Pubspec.yaml
```
name: talkative
description: Talkative - chat loudly!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

    - assets/images/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/talkative_newlogo.png"
  adaptive_icon_background: "assets/images/background.png"
  adaptive_icon_foreground: "assets/images/fg.png"
```
