### ISSUE TITLE
When app is in the background, Android icon is displayed instead of app icon

### ISSUE THREAD

**Issue by dave-k** [fluttercommunity/flutter_launcher_icons#192]
Version 0.7.5
Android 10

How to display the app icon when the app is in the background?
The app icon is displayed in the tray and on the splash screen, 
but the generic android icon is displayed when the app is in the background.
The app icon is displayed on iOS.

<img width="317" alt="app-icon-missing" src="https://user-images.githubusercontent.com/5447484/89953786-9fe78c80-dbe4-11ea-9023-89a1eb1ec14a.png">

pubspec.yaml
````
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rflutter_alert: ^1.0.3
  flutter_sms: 2.0.0+2
  url_launcher: ^5.5.0
  pin_entry_text_field: ^0.1.4
  pin_code_fields: ^3.1.2
  date_field: ^0.1.2
  mask_text_input_formatter: ^1.0.6
  flutter_holo_date_picker: ^0.1.3+3
  package_info: ">=0.4.1 <2.0.0"
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  cloud_functions: ^0.5.0
  email_validator: ^1.0.5
  firebase_messaging: ^6.0.16
  get: ^3.1.2
  location: ^3.0.2
  geocoder: ^0.2.1
  video_player: ^0.10.11+2

  google_sign_in: ^4.5.0
  provider: ^4.1.3
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.8.1
  enum_to_string: ^1.0.9
  datetime_picker_formfield: ^1.0.0
  firebase_auth: ^0.16.1
  flutter_spinkit: ^4.1.2+1
  firebase_auth_web: ^0.1.3+1
  flutter_launcher_icons: ^0.7.5
  cached_network_image: ^2.2.0+1
  image_cropper: ^1.2.1
  image_picker: ^0.6.7+4
  firebase_storage: ^3.1.6
  path: ^1.6.4 # flutter_test
  flutter_tindercard: ^0.1.8
  flutter_hooks: ^0.9.0
  shared_preferences: ^0.5.7+3
  flutter_range_slider: ^1.4.0
  multiselect_formfield: ^0.1.2
  flutter_multiselect: ^0.4.0
  multiple_select: ^0.1.22
  numberpicker: ^1.2.0
  strings: ^0.1.2
  camera: ^0.5.8+2
  cloud_firestore: ^0.13.7

  flutter_google_places: # 0.2.5  # Unhandled Exception: Bad state: Cannot add new events after calling close
    path: ./lib/plugins/flutter_google_places

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
# flutter_icons configuration option
flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/icon.png
    - assets/images/icon-512.png
    - assets/images/placeholder-profile.png
    - assets/images/blank-image.png
    - assets/images/placeholder-image.png
    - assets/images/google_logo.png
    - assets/images/apartment-2.jpeg
    - assets/data/property.json
    - assets/map/map_style.json
    - assets/map/grn-circle.png
````
