### ISSUE TITLE
[BUG] flutter_launcher_icons.yaml is ignored if flutter_launcher_icons-<FLAVOR>.yaml is present

### ISSUE THREAD

**Issue by britannio** [fluttercommunity/flutter_launcher_icons#198]
### :information_source: Info

Version: `e.g. v0.8.0`

### :speech_balloon: Description

My Android app has two flavors: `dev` and `prod`. 
`android/app/src` looks like this:
```
.
├── debug
├── dev
├── main
└── profile
```
Icons for the dev flavor should go under the `/dev` and icons for the prod flavor should go under `/main` hence why I'm not using a `flutter_launcher_icons-prod.yaml` config.

Unfortunately, since adding `flutter_launcher_icons-dev.yaml`, my `flutter_launcher_icons.yaml` file is ignored so updates to it aren't reflected in `/main`

### :scroll: flutter_launcher_icons.yaml
```
flutter_icons:
  android: true
  ios: true
  # IOS settings
  image_path_ios: "dev_assets/ios_launcher_icon.jpg"
  # Android settings
  image_path_android: "dev_assets/android_launcher_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "dev_assets/android_adaptive_launcher_icon.png"
```

### :scroll: flutter_launcher_icons-dev.yaml
```
flutter_icons:
  android: true
  ios: true
  # IOS settings
  image_path_ios: "dev_assets/ios_launcher_icon_dev.jpg"
  # Android settings
  image_path_android: "dev_assets/android_launcher_icon_dev.png"
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "dev_assets/android_adaptive_launcher_icon.png"
```
