### ISSUE TITLE
[BUG] New icon dont change in recents and settings.

### ISSUE THREAD

**Issue by And96** [fluttercommunity/flutter_launcher_icons#208]
I have added those lines in **pubspec.yaml**

`dev_dependencies:`
`  flutter_test:`
`    sdk: flutter`
 ` flutter_launcher_icons: "^0.8.0"`

`flutter_icons:`
`  android: "launcher_icon"`
`  ios: true`
`  image_path: "assets/icon/icon.png"`

I run the following command:
`flutter clean`
`flutter pub get`
`flutter pub run flutter_launcher_icons:main`

The icon is OK only on the home page, but **in settings and in recents it still shows the default old Flutter icon.**
I tried uninstall and install again... Flutter clean... but it didn't help.

Device:
Android 10
MIUI 12

Any ideas?

**Comment by andresraciness** [comment]
I have the same problem with xiaomi redmi note 8, miui 11.0.11, any solution to this problem? but this happened to me when i renamed andriod and ios packages. In my case, the application icon appears, but in services such as GPS and in the open applications bar. If there is any solution to this issue.

**Comment by And96** [comment]
Up

**Comment by aghyad97** [comment]
same issue here

**Comment by oliverraf** [comment]
Same Up!

**Comment by pxsanghyo** [comment]
Same issue in iOS.

**Comment by fnoceda** [comment]
same issue on android, any solution?

**Comment by And96** [comment]
I finally found a solution!

Here is the config in **pubspec.yaml**

```
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" 
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  remove_alpha_ios: true
```

Now, all icons appear correctly even on MIUI.
