### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by personalizedrefrigerator** [fluttercommunity/flutter_launcher_icons#214]
### :information_source: Info
Version: `0.8.1`

### :speech_balloon: Description

It looks like non-square images are squished, rather than padded. This also happens when iOS (and possibly Android) launcher icons are created.

These images are from the `example` project directory.

#### Original (iOS)

![image](https://user-images.githubusercontent.com/46334387/97780049-708b5080-1b3f-11eb-8676-572a3cc5fd5e.png)

#### Generated (iOS)

![image](https://user-images.githubusercontent.com/46334387/97780032-53ef1880-1b3f-11eb-8eb3-f40f91361979.png)

Is this expected behavior?

### :scroll: Pubspec.yaml
```yaml
name: example
description: A new Flutter project to quickly test flutter_launcher_icons.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_launcher_icons:
    path: ../..

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/icon-710x599-android.png"
  image_path_ios: "assets/images/icon-710x599-ios.png"
  image_path_web: "assets/images/icon-710x599-web.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  web: true # Can't specify file name here at present.
  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
