### ISSUE TITLE
[BUG] 15 unassigned children (iOS)

### ISSUE THREAD

**Issue by tamoyal** [fluttercommunity/flutter_launcher_icons#221]
### :information_source: Info
Version: 0.8.1

### :speech_balloon: Description
Icons generated successfully:
```
flutter pub run flutter_launcher_icons:main
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.8.0)
  ════════════════════════════════════════════

• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon

✓ Successfully generated launcher icons
```

However the icon is the missing icon on my iPhone after building and XCode tells me there are 15 missing children.

![Screen Shot 2020-12-15 at 3 27 42 PM](https://user-images.githubusercontent.com/46859/102274978-57b9dd00-3eea-11eb-837b-dbd93c35181e.png)

### :scroll: Pubspec.yaml

Relevant parts of pubspec.yaml:

```
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  ...

dev_dependencies:
  flutter_launcher_icons: "^0.8.1"
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
```

**Comment by FDuhen** [comment]
Same here.
Flutter 1.22.5 • channel stable

I don't get what is causing this problem, but the reason the items are displayed as Unassigned is because the file 
ios/Runner/AppIcon.appiconset/Contents.json is empty whereas it should be indexing every image generated.

Editing the Contents.json file manually fixes the problem.

**Comment by troyshu** [comment]
@FDuhen what did you edit your Contents.json file to / what are the contents? Also, my Contents.js isn't empty and I'm still getting this issue after running `flutter_launcher_icons` (15 unassigned children)

**Comment by troyshu** [comment]
Figured out how to fix the issue of a "corrupted Contents.json" manually, my Contents.json was missing "filename" keys for some reason so I added those manually. Example:
```
{
    "images": [
        {
            "filename": "Icon-App-20x20@2x.png",
            "idiom": "iphone",
            "scale": "2x",
            "size": "20x20"
        },
...
```

I think the source of this issue is Contents.json getting changed or "corrupted" before installing `flutter_launcher_icons`, e.g. the user trying to set up their app icons before discovering `flutter_launcher_icons` (my case). Seems like `flutter_launcher_icons` [won't](https://github.com/fluttercommunity/flutter_launcher_icons/blob/340fa6cead828ec9ffc8ee94cb89e65baa723f58/lib/ios.dart#L72) re-create Contents.json if `ios: true` in `pubspec.yaml`. It'll only re-create Contents.json if you specify your own "app icon flavor" OR you pass a string icon name, and it'll [create](https://github.com/fluttercommunity/flutter_launcher_icons/blob/340fa6cead828ec9ffc8ee94cb89e65baa723f58/lib/ios.dart#L58) the .appiconset folder with that string, with a brand new Contents.json.

**Comment by L3odr0id** [comment]
Finally I found an automatic way how to fix it. You should set ` ios: "AppIcon"`. After the `flutter pub run flutter_launcher_icons:main` the contents.json will be updated and XCode will automatically see the new icons asset.

So for my `flutter_launcher_icons.yaml` is:
```yaml
flutter_icons:
  android: true
  ios: "AppIcon" # Crucial step
  image_path: "assets/icon/launcher.png"
  remove_alpha_ios: true
```

Note: I'm using `flutter_launcher_icons: ^0.9.2`
