### ISSUE TITLE
[BUG]  It DOES, NOT, WORK

### ISSUE THREAD

**Issue by hoangknguyen1807** [fluttercommunity/flutter_launcher_icons#223]
### :information_source: Info

Version: `0.8.1`

### :speech_balloon: Description

I created _assets/icons/_ directory and put an PNG image file inside it, _assets/_ and _pubspec.yaml_ are in the same folder, and  I also configured the pubspec.yaml file following the instructions, but it - doesn - not - work. Could you tell me why?
![image](https://user-images.githubusercontent.com/52640775/103103607-9cfdad80-4654-11eb-963d-9ffe78192d94.png)

### :scroll: Pubspec.yaml

```
name: flutter_app_01
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  english_words: ^3.1.5
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/github.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```
