### ISSUE TITLE
[BUG] Won't generate android icons v0.8.1

### ISSUE THREAD

**Issue by coreagile** [fluttercommunity/flutter_launcher_icons#224]
### :information_source: Info

Version: `e.g. v0.8.1`

### :speech_balloon: Description

Generates iOS icons, but does not generate the android ones. Exits with exit code -9.

### Output
```
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.8.0)
  ════════════════════════════════════════════

• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
pub finished with exit code -9
```

### :scroll: Pubspec.yaml

pubspec.yaml (dev_dependencies only):
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: "^0.8.0"
```

flutter_launcher_icons.yaml:
```
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon-rocket.png"

```

**Comment by coreagile** [comment]
The issue was antivirus software detecting dart as ransomware due to how the image generator was accessing disk. Replacing the antivirus software with something else fixed it!

**Comment by silasrm** [comment]
Hi,

I'm getting this error:
```
Error type 3
           Error: Activity class {br.com.market/br.com.market.MainActivity} does not exist.
[        ] Waiting for observatory port to be available...
```

Config:
```
dependencies:
  //....
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "ic_launcher" # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  image_path_android: "assets/images/playstore.png"
  image_path_ios: "assets/images/appstore.png"
```

AndroidManifest.xml:
```
<application
        android:name="io.flutter.app.FlutterApplication"
        android:label="marketgo"
        android:requestLegacyExternalStorage="true"
        android:usesCleartextTraffic="true">
```

Any idea?
