### ISSUE TITLE
[BUG] IconRound not being generated

### ISSUE THREAD

**Issue by tapizquent** [fluttercommunity/flutter_launcher_icons#226]
### :information_source: Info

Version: `e.g. v0.8.1`

### :speech_balloon: Description

New version of Android require a new tag in the application `android:roundIcon="@mipmap/ic_launcher_round"` in order to render the round icons. If this is not provided, it tries to render a square icon and fits it to the circle, leaving some white space round which looks horrible.

It would be good for this package to not only generate the Square icons, but to also include this round ones so that the icons looks good across all devices.

### :scroll: Pubspec.yaml

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"
```

**Comment by lechnerio** [comment]
I'm trying to get this working and when using only the `image_path` this is what the icons look like on ios (left) and android (right).

![ios-vs-android](https://user-images.githubusercontent.com/591317/106256322-6864af00-621b-11eb-9e4c-03fbee4b9163.png)

when using `adaptive_icon_foreground` and `adaptive_icon_background` instead, the icon's foreground get's scaled up (tested on pixel and oneplus devices.)

![Screenshot 2021-01-29 at 10 20 13](https://user-images.githubusercontent.com/591317/106256670-de691600-621b-11eb-956e-5de10c37c451.png)

**Comment by Naphier** [comment]
Not sure how to get this to work,  Testing on Pixel 4 with Android 11.

```
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  icon_adaptive_foreground: "assets/icon.png"
  icon_adaptive_background: "#000000"
```

![Screenshot_20210214-200022](https://user-images.githubusercontent.com/10132540/107894957-7a26a180-6eff-11eb-9939-c12cdc0e7c9c.png)

**Comment by Techno-Disaster** [comment]
Any updates on this?

**Comment by dsgriffin** [comment]
> I'm trying to get this working and when using only the `image_path` this is what the icons look like on ios (left) and android (right).
> 
> ![ios-vs-android](https://user-images.githubusercontent.com/591317/106256322-6864af00-621b-11eb-9e4c-03fbee4b9163.png)
> 
> when using `adaptive_icon_foreground` and `adaptive_icon_background` instead, the icon's foreground get's scaled up (tested on pixel and oneplus devices.)
> 
> ![Screenshot 2021-01-29 at 10 20 13](https://user-images.githubusercontent.com/591317/106256670-de691600-621b-11eb-956e-5de10c37c451.png)

Did you find a solution for the `adaptive_icon_foreground` issue? Seems it doesn't scale correctly. Can see there's a PR #181 that might help if merged.

**Comment by emptyopen** [comment]
bumping, i also would like this fixed

**Comment by flutter-clutter** [comment]
I have the same problem. Fix would be appreciated.

**Comment by sooxt98** [comment]
Im using this as a workaround

``` yaml
dev_dependencies:
  flutter_launcher_icons:
    git:
        url: https://github.com/knyghtryda/flutter_launcher_icons
        ref: scaling

dependency_overrides:
  yaml: ^3.1.0
  image: ^3.0.2
```
