### ISSUE TITLE
[BUG] Ignoring by Background

### ISSUE THREAD

**Issue by christopherkube** [fluttercommunity/flutter_launcher_icons#231]
### :speech_balloon: Description
After running both
```
flutter pub get
flutter pub run flutter_launcher_icons:main
```
My App Icon (on Android Emulator and pysical huawei p30 pro) only contains the foreground. **The background is missing.**

### :scroll: Pubspec.yaml
```
flutter_launcher_icons: ^0.8.1

flutter:
  assets:
    - lib/assets/app_icon/

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/app_icon/appicon_total.png'
  adaptive_icon_foreground: 'lib/assets/app_icon/appicon_background.png'
  adaptive_icon_background: 'lib/assets/app_icon/appicon_foreground.png'
```
