### ISSUE TITLE
[BUG] Running is successful but it breaks ios/Runner.xcodeproj/project.pbxproj

### ISSUE THREAD

**Issue by AndiGrass** [fluttercommunity/flutter_launcher_icons#238]
### :information_source: Info
Version: `v0.8.1`

### :speech_balloon: Description

Execution prints no errors, but it adds some random (maybe the last n chars from the file) to ios/Runner.xcodeproj/project.pbxproj so it gets broken.

Example:
Before running: 

```
/* End XCConfigurationList section */
	};
	rootObject = 97C146E61CF9000F007C117D /* Project object */;
}
```

after running:
```
/* End XCConfigurationList section */
	};
	rootObject = 97C146E61CF9000F007C117D /* Project object */;
}7D /* Project object */;
}
}
``` 

It adds more lines upon every execution. If I remove those generated lines app icons are working correctly.

### :scroll: Pubspec.yaml

```
name: eventcalendar
description: A generic event calendar

version: 0.2.0

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  pedantic: '>=1.8.0'
  flutter_cupertino_localizations: '>=1.0.1'
  cupertino_icons: '>=0.1.3'
  flutter_platform_widgets: '>=0.51.0'
  http: '>=0.12.2'
  flutter_linkify: '>=3.1.3'
  url_launcher: '>=5.5.0'
  dio: '>=3.0.8'
  provider: '>=4.0.1'
  shared_preferences: '>=0.5.6'
  oktoast: '>=2.3.0'
  table_calendar: '>=2.2.2'
  collection: '>=1.14.12'
  flutter_icons: '>=1.0.0+1'
  line_icons: '>=0.2.0'
  pull_to_refresh: '>=1.6.4'
  animated_background: '>=1.0.5'
  flutter_svg: '>=0.15.0'
  webview_flutter: '>=2.0.1'
  ext_video_player: '>= 0.0.6'
  uni_links:

dev_dependencies:
  flutter_launcher_icons: '>=0.8.1'
  flutter_test:
    sdk: flutter


```
