### ISSUE TITLE
Target file "flutter_launcher_icons:main" not found.

### ISSUE THREAD

**Issue by luishar0** [fluttercommunity/flutter_launcher_icons#244]
### :information_source: Info
Version: `v0.9.0`

### :speech_balloon: Description
Trying to create icons on an M1 MacBook Air not working. 
I don't get any errors or dependency problems on `pub get`
But when running: `flutter run flutter_launcher_icons:main`
I get error: Target file "flutter_launcher_icons:main" not found.

### :scroll: Pubspec.yaml

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_storage: ^8.0.0
  cloud_firestore: ^1.0.0

  google_sign_in: ^5.0.0
  provider: ^5.0.0
  rxdart: ^0.26.0

  cached_network_image: ^3.0.0-nullsafety
  flutter_svg: ^0.21.0-nullsafety.0
  
  agora_rtc_engine: ^3.2.1
  permission_handler: ^6.0.1

  image_picker: ^0.7.2
  image_cropper: ^1.4.0
  file_picker: ^3.0.0
  table_calendar: ^3.0.0-nullsafety.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  image_path: 'assets/logo4.jpg'
  android: true
  ios: true

```
