### ISSUE TITLE
[BUG] Error: Activity class {...MainActivity} does not exist.

### ISSUE THREAD

**Issue by silasrm** [fluttercommunity/flutter_launcher_icons#246]
### :information_source: Info
Version: ^0.8.1

### :speech_balloon: Description
In development, when I'll running the app, this error occurs and stop the compiling: 

```
Error type 3
           Error: Activity class {br.com.market/br.com.market.MainActivity} does not exist.
[        ] Waiting for observatory port to be available...
```

### :scroll: Pubspec.yaml

```
name: market
description: Market

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  credit_card_type_detector: ^1.1.0
  cupertino_icons: ^0.1.3
  connectivity: ^2.0.2
  data_connection_checker: ^0.3.4
  graphql_flutter: ^4.0.1
  graphql: ^4.0.1
  tinycolor: 1.0.3
  url_launcher: ^5.7.10
  flutter_open_whatsapp: ^0.1.2
  http: ^0.12.2
  flutter_masked_text: ^0.8.0
  cpf_cnpj_validator: ^1.0.5
  phone_number: ^0.8.1+1
  datetime_picker_formfield: ^1.0.0
  encrypted_shared_preferences: ^1.0.7
  string_validator: ^0.1.4
  flutter_local_notifications: ^1.4.4+2
  package_info: ^0.4.3+4
  fluttertoast: ^7.0.1
  qrscan: ^0.2.22
  carousel_slider: ^2.2.1
  intl: ^0.16.1
  dotted_border: ^1.0.7
  esys_flutter_share: ^1.0.2
  progress_indicator_button: ^0.0.3
  onesignal_flutter: ^2.0.0
  get_version: ^0.2.2
  photo_view: ^0.10.3
  event_hub: ^0.1.1
  image_picker: ^0.6.7+22
  barcode_flutter: ^1.1.2
  permission_handler: ^5.1.0+2
  flutter_dotenv: ^3.1.0
  provider: ^4.3.3
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  gql_code_gen: ^0.1.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/creditcards/
    - assets/images/playstore.png
    - assets/images/appstore.png

flutter_icons:
  android: true   # OR with this:  android: "ic_launcher"
  ios: true
  adaptive_icon_background: "#FFFFFF" # OR without this config
  image_path_android: "assets/images/playstore.png" # OR using only image_path param
  image_path_ios: "assets/images/appstore.png"
```
