### ISSUE TITLE
[BUG] How to remove alpha in image ? 

### ISSUE THREAD

**Issue by javierbm7** [fluttercommunity/flutter_launcher_icons#253]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by sarveshbhatnagar** [comment]
+1 Facing the same issue. If an image contains alpha channel then it fails for iOS validation.

**Comment by swbliss** [comment]
In version 0.9.0, the option to remove alpha channel for iOS icons is added (https://pub.dev/packages/flutter_launcher_icons)
You can activate this option by adding `remove_alpha_ios` option like this.
```
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
```
