### ISSUE TITLE
[BUG] Cannot run generator, requires `--sound-null-safety`

### ISSUE THREAD

**Issue by cameron-sonocent** [fluttercommunity/flutter_launcher_icons#261]
### :information_source: Info

Version: `0.9.0`

### :speech_balloon: Description

When trying to run `flutter pub run flutter_launcher_icons:main`, I get the following error:
```
Unable to spawn isolate: error: Library 'file:///Users/cameron/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.0/bin/main.dart' was compiled with sound null safety (in strong mode) and it requires --sound-null-safety option at runtime
pub finished with exit code 1
```

Passing in `--sound-null-safety` doesn't change the error (neither does `--no-sound-null-safety`).

### :scroll: Pubspec.yaml

```
name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:
  integration_test:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/images/icon_no_alpha.png
  image_path_android: assets/images/icon_with_alpha.png
  adaptive_icon_background: assets/images/icon_adaptive_background.png
  adaptive_icon_foreground: assets/images/icon_adaptive_foreground.png
```

Note that although the version constraint here is `>=2.12.0`, this is a minimal reproducible example, the actual project I'm working on has `>=2.6.0`, and the same errors persist

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.4)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

• No issues found!
```
