### ISSUE TITLE
Dependence on older args 2.0.0 makes other packages incompatible

### ISSUE THREAD

**Issue by Zelfapp** [fluttercommunity/flutter_launcher_icons#262]
### :information_source: Info

Version: `^0.9.0`

### :speech_balloon: Description

Because flutter_native_splash >=1.1.9 depends on args ^2.1.1 and flutter_launcher_icons 0.9.0 depends on args 2.0.0, flutter_native_splash >=1.1.9 is incompatible with flutter_launcher_icons 0.9.0.

Please update args to min `^2.1.1`.

### :scroll: Pubspec.yaml

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.0
```
