### ISSUE TITLE
[BUG] Flavors not being detected

### ISSUE THREAD

**Issue by Zazo032** [fluttercommunity/flutter_launcher_icons#279]
### :information_source: Info

Version: `0.9.1`

### :speech_balloon: Description

We're using flavors for our app, so instead of adding the `flutter_icons` to `pubspec.yaml`, following the flavor's section on `README.md`, we created 2 files: `flutter_launcher_icons-development.yaml` and `flutter_launcher_icons-production.yaml`, at the same project level as `pubspec.yaml`.

#### Error log
```
flutter pub run flutter_launcher_icons:main
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.9.1)
  ════════════════════════════════════════════


✗ ERROR: NoConfigFoundException
Check that your config file `flutter_launcher_icons.yaml` has a `flutter_icons` section
pub finished with exit code 1
```

### :scroll: `pubspec.yaml`

```yaml
name: <elided>
description: <elided>
publish_to: none
version: 0.0.3+6

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  <elided>

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.2.0

flutter:
  assets:
    - assets/auth/
  generate: true
  uses-material-design: true
```

### :scroll: `flutter_launcher_icons-development.yaml`

```yaml
flutter_icons:
  android: true
  image_path: "assets/native/icon-development.png"
```

### :scroll: `flutter_launcher_icons-production.yamll`

```yaml
flutter_icons:
  android: true
  image_path: "assets/native/icon-development.png"
```
