### ISSUE TITLE
Black icon on Android

### ISSUE THREAD

**Issue by erperejildo** [fluttercommunity/flutter_launcher_icons#280]
### :information_source: Info

Version: 0.9.1

### :speech_balloon: Description

I have a 1024x1024 icon which generates just a black icon. For iOS works ok. When I check the folders inside /res I see an old icon but this one is not even displayed.

command:
flutter pub run flutter_launcher_icons:main

code:
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'

output:
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.9.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon

✓ Successfully generated launcher icons

icon:
![icon](https://user-images.githubusercontent.com/5629919/130040020-1cf65630-e21e-495c-a45e-01de6eaf82d4.png)

### :scroll: Pubspec.yaml

```
name: my_rents
description: Manage your properties and their rents easily

version: 3.2.1+3.2.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  line_icons: ^2.0.1
  dapackages: ^1.6.0 # keeps packages updated
  flutter_cupertino_localizations: ^1.0.1
  flutter_google_places: ^0.3.0
  google_mobile_ads: ^0.13.3 # needs Info.plist modification
  maps_launcher: ^2.0.0 # REMOVED, USE OTHER INSTEAD
  uuid: ^3.0.4 # IDs for events
  cloudinary_public: ^0.8.1+1
  provider: ^5.0.0
  cloud_firestore: ^1.0.7 # needs Info.plist modification
  firebase_core: ^1.1.0 # needs Runner/GoogleService-Info.plist
  firebase_auth: ^1.1.3 # needs Runner/GoogleService-Info.plist
  firebase_analytics: ^8.0.2 # needs Runner/GoogleService-Info.plist
  firebase_crashlytics: ^2.0.2 # needs Runner/GoogleService-Info.plist and NSAppTransportSecurity in Info.plist
  http: ^0.13.1
  badges: ^2.0.1
  flutter_translate: ^3.0.1
  flutter_facebook_auth: ^3.3.3+1
  google_sign_in: ^5.0.2 # needs Info.plist modification
  sign_in_with_apple: ^3.0.0  # needs Xcode modification https://pub.dev/packages/sign_in_with_apple
  shared_preferences: ^2.0.5
  share_plus: ^2.1.4
  intl: ^0.17.0 # locales for table_calendar and datetime manipulation
  flutter_downloader: ^1.6.1 # needs Xcode modification https://pub.dev/packages/flutter_downloader
  jiffy: ^4.1.0 # date manipulation
  permission_handler: ^7.0.1 # needs Info.plist modification
  path_provider: ^2.0.1
  after_init: ^0.1.2 # NO NULL
  flutter_email_sender: ^5.0.0
  flutter_launcher_icons: ^0.9.1
  file_picker: ^3.0.1 # for multiple images selection
  image_picker: ^0.7.4 # for camera
  image: ^3.0.2
  url_launcher: ^6.0.9 # needs Info.plist modification
  transparent_image: ^2.0.0
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_slidable: 1.0.0-dev.8
  flutter_svg: ^0.22.0
  table_calendar: ^3.0.0
  add_2_calendar: ^2.1.0 # Info.plist modification
  flutter_local_notifications: ^5.0.0+3
  contacts_service: ^0.6.1 # get contacts. Info.plist modification
  in_app_purchase: ^0.5.2
  device_info: ^2.0.0
  flutter_platform_widgets: ^1.5.0
  flutter_native_splash: ^1.1.8+4
  intl_phone_number_input: ^0.7.0+1  # NO NULL
  country_pickers: ^2.0.0
  currency_picker: ^2.0.3
  #  country_currency_pickers: ^1.0.1 # NO NULL
  reorderables: ^0.4.1 # NO NULL reorder rent fields
  drag_and_drop_gridview: ^1.0.8 # NO NULL
  pdf: ^3.3.0
  printing: ^5.2.1 # necessary for the above one
  open_file: ^3.2.0 # necessary for the above one
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety

# generate new splashscreen: flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/splashscreen.png
  color: '281b60'
  fill_horizontal: true

# generate new icon: flutter pub get && flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/images/icon.png'
#  adaptive_icon_background: '#281B60' <--- THIS ALSO DOESN'T WORK
#  image_path_ios: 'assets/images/icon.png'
#  image_path_android: 'assets/images/icon.png'
#  adaptive_icon_background: 'assets/images/icon.png'
#  adaptive_icon_foreground: 'assets/images/icon.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/images/versions/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

```
