### ISSUE TITLE
[BUG] pubspec.lock file has changed error message

### ISSUE THREAD

**Issue by lastmeta** [fluttercommunity/flutter_launcher_icons#281]
### :information_source: Info
Version: `e.g. v0.9.1`

### :speech_balloon: Description
I followed the instructions (trying flutter_launcher_icons in both dependencies and dev_dependencies)
making a file next to pubspec.yaml called flutter_launcher_icons.yaml containing:
```
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/rvn256.png"
```
but got this message:
```
c:\repos\project>flutter pub get
Running "flutter pub get" in raven_mobile...                     1,051ms

c:\repos\project>flutter pub run flutter_launcher_icons:main
The pubspec.lock file has changed since the .dart_tool/package_config.json file was generated, please run "pub get" again.
pub finished with exit code 65
```

### :scroll: Pubspec.yaml
```
name: raven_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  flutter_dotenv: ^5.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  qr_flutter: ^4.0.0
  raven:
    path: /moontree/repos/raven
    #git: https://github.com/moontreeapp/raven.git
  cupertino_icons: ^1.0.2
  settings_ui: ^1.0.0
  flutter_treeview: ^1.0.6+1
  flutter_launcher_icons: "^0.9.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
```

**Comment by akvus** [comment]
Looks like including a package by path may be the issue.

```
raven:
    path: /moontree/repos/raven
```

**Comment by lastmeta** [comment]
that works fine without flutter launch icons - you're saying there's a negative interaction?

**Comment by akvus** [comment]
I run into the same error by endeavouring to run `flutter_launcher_icons` with following dependencies:

```
dependencies:
  test_pcg:
    path: package/test_pcg
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_gen: ^3.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
```

It seems there was some conflict between `flutter_gen` and the `test_pcg` (a bootstrapped empty package) once any of the two is removed, then `flutter_launcher_icons` works. In my case the issue was solved by changeing `flutter_gen` to `flutter_gen_runner`. 

Regarding your case, I don't know. I copied your dependency list and replaced `raven` with my `test_pcg`. Afterwords `flutter_launcher_icons` worked impeccably. Maybe the issue is within `raven`.
