### ISSUE TITLE
[BUG] - Multitasking logo background color error

### ISSUE THREAD

**Issue by Macacoazul01** [fluttercommunity/flutter_launcher_icons#287]
### :information_source: Info

Version: `e.g. v0.9.2`

### :speech_balloon: Description

The background color of the app on the store/home menu is different than the one on the multitasking tab. The first one is white (ok), and the second is blue.

![home](https://user-images.githubusercontent.com/57464965/133307299-efe32545-06af-43eb-b5c6-2d5115f1e572.png)
![Inkedmenu_LI](https://user-images.githubusercontent.com/57464965/133307304-798be53e-3c8d-4a50-8cd9-1a668f44883b.jpg)
![multitask](https://user-images.githubusercontent.com/57464965/133307311-1a6f0678-1ff5-400b-b208-564f10040284.png)

### :scroll: Pubspec.yaml

```
name: oioio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-96.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
 android: true
 ios: true
 image_path: "images/isotipo.png"
 remove_alpha_ios: true
 adaptive_icon_foreground: "#ffffff" 
flutter:
  uses-material-design: true
```
