### ISSUE TITLE
[BUG] App launcher icon broken/crashed (iPhone Simulator, iOS 14.4)

### ISSUE THREAD

**Issue by kws1207** [fluttercommunity/flutter_launcher_icons#300]
### :information_source: Info

Version: `0.9.2`

### :speech_balloon: Description

I'm struggling with changing App Launcher Icon using flutter_launcher_icons package, on my iPhone Simulator (iOS 14.4).

In my `pubspec.yaml`:

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  #image_path_android: "assets/icon.png"
  image_path: "assets/icon.png"
  android: false
  ios: true
```

On VScode terminal (in my project root directory):
```
> flutter pub run flutter_launcher_icons:main
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.9.1)                               
  ════════════════════════════════════════════
  
• Overwriting default iOS launcher icon with new icon

✓ Successfully generated launcher icons

> flutter run                     ✔
Multiple devices found:
Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android
11 (API 30) (emulator)
iPhone 12 Pro Max (mobile)         • 0A68628E-A233-40C2-8B07-504F23A5FD81 • ios         •
com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
[1]: Android SDK built for x86 (emulator-5554)
[2]: iPhone 12 Pro Max (0A68628E-A233-40C2-8B07-504F23A5FD81)
Please choose one (To quit, press "q/Q"): 2
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                             16.4s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        15.4s
Xcode build done.                                           267.2s
Syncing files to device iPhone 12 Pro Max...                        90ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

An Observatory debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:51673/MS0nx6nWyeg=/
The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:51673/MS0nx6nWyeg=/
```

But in the Simulator, app launcher icon is broken ('Runner' is the App):

[![enter image description here][1]][1]

In `~/ios/Runner/Assets.xcassets/AppIcon.appiconset/`, I can see that the image files are correctly changed.

How can I fix this? Maybe it's not package problem, but iOS build problem??

p.s. I've tried `flutter clean` and `flutter run` multiple times, it still remains same.

  [1]: https://i.stack.imgur.com/vE5ts.png

### :scroll: Pubspec.yaml

```
name: where_to_eat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^4.1.0
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  firebase_crashlytics: ^2.3.0
  google_sign_in: ^4.5.9
  cloud_firestore: ^2.3.0
  flutter_secure_storage: ^3.3.5
  #kopo: "^0.1.3"
  kpostal: ^0.3.2
  flutter_slidable: ^0.6.0
  http_parser: ^4.0.0
  http: ^0.13.3
  flutter_spinning_wheel: ^1.1.0
  url_launcher: ^6.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  geolocator: ^7.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  #image_path_android: "assets/icon.png"
  image_path: "assets/icon.png"
  android: false
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/logos/apple.png
    - assets/logos/google.png
    - assets/images/splash_img.jpeg
    #- assets/images/crown.png
    - assets/images/wheel-6-300.png
    - assets/images/roulette-center-300.png
    - assets/icon.png
    
    # # An image asset can refer to one or more resolution-specific "variants", see
  # #https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts: 
    - family: BMDH
      fonts:
      - asset: assets/fonts/BMDOHYEON_ttf.ttf
    - family: BMYS
      fonts:
      - asset: assets/fonts/BMYEONSUNG_ttf.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
