### ISSUE TITLE
[BUG] I cannot fill the icon background with the instructions offered using 'adaptive_icon_background'. Does not work. Could you give an example of how to use it?

### ISSUE THREAD

**Issue by lindomarfarineli** [fluttercommunity/flutter_launcher_icons#302]
flutter_icons:
    android: true
    ios: true
    image_path: "icons/transparente.png"
    adaptive_icon_background: "#FF5a49b0"

would it be this?
if it is it doesn't work.

**Comment by AlmogRnD** [comment]
The same issue, following

**Comment by AlmogRnD** [comment]
I was able to fix it by doing the following 

```
flutter_icons:
  image_path_android: "assets/images/ic_launcher.png"
  image_path_ios: "assets/images/ic_launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "#e76f51" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" 
```

**Comment by aoatmon** [comment]
on android 12 
that the icon background is wrong (white) in the launcher, 
but correct (black) when you minimize the app

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-EE)
    • Flutter version 2.5.3 at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```
```yaml
environment:
  sdk: '>=2.14.4 <3.0.0'
  flutter: ^2.5.3

dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  android: true
  ios: true
  image_path: images/logo.png
  adaptive_icon_background: '#000000'
  remove_alpha_ios: true
```
