### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RoarGronmo** [fluttercommunity/flutter_launcher_icons#304]
### :information_source: Info

Version: `0.9.2`

### :speech_balloon: Description

Unable to change icon background with:

```
#---Icons---

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_round.png"
  adaptive_icon_background: "#666666"


dev_dependencies:
  flutter_test:
    sdk: flutter

  #---Launcher icons---
  flutter_launcher_icons: ^0.9.2
```

### :scroll: Pubspec.yaml

```
name: mwork
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  msal_js: ^2.14.0
  aad_oauth: ^0.3.0
  provider: ^6.0.1
  path_to_regexp: ^0.4.0
  quiver: ^3.0.0
  introduction_screen: ^2.1.0
  intl: ^0.17.0
  flutter:
    sdk: flutter

  #--jwt--- makes it possible to analyze jwt

  jwt_decode: ^0.3.1

  #---Swagger changes---
  chopper: ^4.0.3
  json_annotation: ^4.3.0

  #---Google Maps---
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2

  #---Location data (GPS)---
  location: ^4.3.0

  #---Get---
  get: ^4.3.8

  #---Settings / preferences ---
  flutter_settings_screens: ^0.3.2-null-safety

  #---Camera function---
  camera: ^0.9.4+5
  path_provider: ^2.0.7
  path: ^1.8.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


#---Icons---

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_round.png"
  adaptive_icon_background: "#666666"


dev_dependencies:
  flutter_test:
    sdk: flutter

  #---swagger changes---
  build_runner: ^2.1.5
  chopper_generator: ^4.0.3
  json_serializable: ^6.0.1
  swagger_dart_code_generator: ^2.2.7

  #---Launcher icons---
  flutter_launcher_icons: ^0.9.2


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



```
