### ISSUE TITLE
[BUG] background color inconsistent on android 12

### ISSUE THREAD

**Issue by aoatmon** [fluttercommunity/flutter_launcher_icons#306]
### :information_source: Info

Version: `v0.9.2`

### :speech_balloon: Description

icon background inconsistent on android 12
to reproduce the issue:

- clone this [repository](https://github.com/aoatmon/icon_background_issue)
- run `flutter pub run flutter_launcher_icons:main`
- run `flutter run --release` on **_android 12 device_** (tested device in the doctor below)

observe inconsistent icon background

in pubspec `#000000`
in launcher `#ffffff`
minimized `"blue"`

### :scroll: Pubspec.yaml

<details>
<summary>pubspec</summary>

```yaml
name: icon_background_issue
description:
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.14.4 <3.0.0'
  flutter: ^2.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: true
  image_path: images/dash.png
  adaptive_icon_background: '#000000'
```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-EE)
    • Flutter version 2.5.3 at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

</details>
