### ISSUE TITLE
[BUG] minSdk error Android

### ISSUE THREAD

**Issue by Areopagitics** [fluttercommunity/flutter_launcher_icons#329]
### :information_source: Info

Version: `flutter_launcher_icons: "^0.9.2"`

### :speech_balloon: Description
Android Icons aren't being generated ... answer is to [write min/maxSdk numbers](https://stackoverflow.com/questions/70611977/flutter-flutter-launcher-icons-error-pub-finished-with-exit-code-255), but this should be done automatically. Please fix.

```
#0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7)
#1      int.parse (dart:core-patch/integers_patch.dart:55:14)
#2      minSdk (package:flutter_launcher_icons/android.dart:309:18)
#3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47)
#4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
#5      main (file:///C:/Users/Missions%2001/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

```

### :scroll: Pubspec.yaml
```
dev_dependencies:
  flutter_native_splash: ^1.3.3
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  change_app_package_name: ^1.0.0

flutter_native_splash:
  android: true
  background_image: "assets/background.png"
  android_gravity: center

flutter_icons:
  android: true
  image_path: "assets/icon.png"
```
