### ISSUE TITLE
[FEATURE REQUEST] minSdk setting in pubspec.yaml to solve issue #324

### ISSUE THREAD

**Issue by Areopagitics** [fluttercommunity/flutter_launcher_icons#330]
### :speech_balloon: Description
The ability to set minSdk setting in pubspec.yaml to solve issue #324. Like this for example:

```
flutter_icons:
  android: true
  image_path: "assets/icon.png"
  minSdk: 16
```

### :question: Platform
Android
