### ISSUE TITLE
[BUG] My app still shows the Flutter icon

### ISSUE THREAD

**Issue by tdkehoe** [fluttercommunity/flutter_launcher_icons#331]
### :information_source: Info

Version: `e.g. v0.9.2`

### :speech_balloon: Description

I set up my icon and flutter_launcher_icons but I'm still seeing the Flutter icon. I'm not getting any error messages.

My icon is a 180x180px PNG file. It's in assets/icon/nachman_180.png.

I'm testing on an Android phone connected to my MacBook. I can't test on my iPhone because of a bug in Bumblebee not finding cocoapods. 

### :scroll: Pubspec.yaml
```
name: kabbalah
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.18
  mailto: ^2.0.0
  pay: ^1.0.7
  flutter_stripe: ^2.1.1

dev_dependencies:
  test: 1.20.1
#  flutter_test:
#    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

  flutter_launcher_icons: ^0.9.2

flutter_icons:
#  android: true // tried this first, didn't work
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/nachman_180.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
```
