### ISSUE TITLE
IOS app icon not showing with flutter_launcher_icons: "^0.9.2"  

### ISSUE THREAD

**Issue by Abdullahfoysal** [fluttercommunity/flutter_launcher_icons#332]
#below is from 0.9.2 documentation which don't work for ios
dev_dependencies:
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  
  
  ## solution: 
  <ios: "launcher_icon"> should be used instead of <ios:true> which works for me

**Comment by andynvt** [comment]
set `ios: "AppIcon"` will replace the existing one. This works for me

**Comment by mrweiland** [comment]
I tried both and none are working for me and also this is not working with Android either :(

```
flutter_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icon/icon.png"
```
