### ISSUE TITLE
[BUG]  ASSETCATALOG_COMPILER_APPICON_NAME Flavor icon

### ISSUE THREAD

**Issue by ghost** [fluttercommunity/flutter_launcher_icons#337]
### :information_source: Info

Version: `0.9.2`

### :speech_balloon: Description

This package edit /ios/Runner.xcodeproj/project.pbxproj in the wrong way : 
We should got 
```
ASSETCATALOG_COMPILER_APPICON_NAME = "AppIcon-flavor-qa-dev";
```
But we got the following : 
```
ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon-flavor;
```
Missing double quote, not full flavor name (must take in consideration all character until .yaml)
This broken the xcode project and we cannot open xcode. 

### :scroll: Pubspec.yaml

```yaml
#flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons-flavor-qa-dev.yaml
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/flavor/logo.png"
  remove_alpha_ios: true

```
