### ISSUE TITLE
[BUG] Background color doesnt work (android)

### ISSUE THREAD

**Issue by IndieRobert** [fluttercommunity/flutter_launcher_icons#338]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Background color doesnt work (android)

### :scroll: Pubspec.yaml

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
  adaptive_icon_background: "#27212f"

**Comment by devj3ns** [comment]
Hey, I think when you want to use `adpative_icon_background` you also have to specify `adpative_icon_foreground` and the image you use as foreground should be a `.png` if you have transparent parts there.

**Comment by iapicca** [comment]
https://github.com/fluttercommunity/flutter_launcher_icons/issues/306

**Comment by romantitov** [comment]
I have the same issue with emulator Android emulator Pixel 5 - API 30 and a real device Device: Galaxy S10e  Android 12

```
dev_dependencies:
  flutter_launcher_icons: "^0.9.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/appiconfg.png"
  adaptive_icon_background: "#40A7E3"
  remove_alpha_ios: true
```

It also doesn't work if I specify `adpative_icon_foreground` and if I set  an image patch for `adaptive_icon_background` I've tried many different combinations of settings.
