### ISSUE TITLE
Restrict filename of generating android icons

### ISSUE THREAD

**Issue by tanakeiQ** [fluttercommunity/flutter_launcher_icons#34]
Android icons cannot use except lowercase letters.

I think that it should be limited when generating.

```bash
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> /Users/tanakei/Documents/flutter-dev/android/app/src/main/res/mipmap-mdpi/app-icon.png: Error: '-' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle build failed: 1
```

**Comment by MarkOSullivan94** [comment]
@tanakeiQ thanks for reporting this!

Could you share your pubspec.yaml flutter_icons config?

**Comment by tanakeiQ** [comment]
@MarkOSullivan94 

okay. thanks.
```yaml
...
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.5.2

flutter_icons:
  android: "app-icon"
  ios: true
#  image_path: "assets/icon/app-icon.png"
  image_path_android: "assets/icon/app_icon_android.png"
  image_path_ios: "assets/icon/app_icon_ios.png"
#  adaptive_icon_background: "#FFFAFAFA"
#  adaptive_icon_foreground: "assets/icon/icon-foreground.png"
```
