### ISSUE TITLE
FileSystemException: Cannot open file, path = 'flutter_launcher_icons*'

### ISSUE THREAD

**Issue by danielwies** [fluttercommunity/flutter_launcher_icons#354]
I have no idea what is going on but I followed multiple guides and did everything they did but for some reason I cant get the package to work. I have two flavors and I'm using a custom configuration file "flutter_launcher_icons-MyFlavor.yaml" for each flavor like so:

```
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  remove_alpha_ios: true
```
When I try to run the command "flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons*" as specified in the docs I get this error.

![image](https://user-images.githubusercontent.com/38783284/160888752-0a13e50c-13d5-427b-b853-72f680ee5d01.png)

I guess there seems to be an issue with the path or whatever?

Does anyone have the same issue or know what my mistake is?

@MarkOSullivan94 after some googling there seem to be more people having that issue, any idea what the problem is?
