### ISSUE TITLE
Unhandled exception: FormatException: Invalid number (at character 1)  ^  #0      int._handleFormatError (dart:core-patch/integers_patch.dart:129:7) #1      int.parse (dart:core-patch/integers_patch.dart:55:14) #2      minSdk (package:flutter_launcher_icons/android.dart:309:18) #3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:94:47) #4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7) #5      main (file:///C:/Users/Heba/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.2/bin/main.dart:6:26) #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32) #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12) pub finished with exit code 255[BUG] 

### ISSUE THREAD

**Issue by hebaea** [fluttercommunity/flutter_launcher_icons#359]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by levi956** [comment]
Same problem

**Comment by codegrue** [comment]
I get the same problem. Here is my config:

```
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "assets/images/app_icon_android_background.png"
  adaptive_icon_foreground: "assets/images/app_icon_android_foreground.png"
```

If I comment out the adaptive items, it works.

**Comment by vensauro** [comment]
Same here
![image](https://user-images.githubusercontent.com/41435789/164312674-8238f095-0a4a-473e-9459-26c22477e3c4.png)

on Dart SDK version 2.16.2 and Flutter 2.10.4

**Comment by vensauro** [comment]
I see that the code tries to read the file build.gradle on this line:
![image](https://user-images.githubusercontent.com/41435789/164316354-2f667eea-2cba-42e2-bac4-6016b2c0d524.png)
and not have numbers on this line

**Comment by vensauro** [comment]
the flutter changed the way to set the minSdkVersion
https://stackoverflow.com/questions/70341325/how-do-i-update-minsdkversion-and-targetsdkversion-in-the-new-version-of-flutter
https://stackoverflow.com/questions/70311685/how-to-update-minsdkversion-in-flutter-updated-2-8

after editing the file, all works fine
![image](https://user-images.githubusercontent.com/41435789/164317421-b80dc068-7c9b-450f-9bca-a4da509a1b83.png)

this can be a workaround yet the package not update

**Comment by mohadel92** [comment]
same problem

**Comment by mohadel92** [comment]
@vensauro  this was the fix thanks

**Comment by cotwitch** [comment]
https://pub.dev/packages/flutter_launcher_icons_maker

**Comment by vensauro** [comment]
> https://pub.dev/packages/flutter_launcher_icons_maker

this is a nice alternative, I think that this repo needs more maintainers, the actual maintainer can not have more time to work here (and that's is ok)

**Comment by jlyonsmith** [comment]
You can also use one of the many fixed forked versions  to get around the problem.  For example:

```yaml
dev_dependencies:
  flutter_launcher_icons:
    git:
      url: git@github.com:RatakondalaArun/flutter_launcher_icons.git
      ref: fix/flutter-v2.8.0-support-321
```

This checks the `local.properties` file for a definition of `minSdkVersion` which you should set to 26 or higher to support Android adaptive icons.  I don't recommend changing the version number directly in the `build.gradle` file as it just makes the project harder to upgrade in the future.
