### ISSUE TITLE
Notice: Seeking maintainer

### ISSUE THREAD

**Issue by MarkOSullivan94** [fluttercommunity/flutter_launcher_icons#363]
Hey all 👋 

Looking to appoint someone to take over maintenance of `flutter_launcher_icons`, please comment if you wish to take over.

Thanks!

**Comment by RatakondalaArun** [comment]
HI @MarkOSullivan94 
I am interested in maintaining this project
I may not have much experience with native android and IOS development but I can help you guys with cleaning up the repository and do my part for the community.

**Comment by bradintheusa** [comment]
I'll volunteer.  I'm a full-time flutter freelancer whos been using flutter since the beta. I have already taken over a few packages.

**Comment by MarkOSullivan94** [comment]
Hi @bradintheusa and @RatakondalaArun, thank you for reaching out and volunteering.

I would love it if **both of you** decide to help maintain flutter_launcher_icons.

I notice @RatakondalaArun has already submitted a PR #322 (thanks for adding the closing keywords to auto close the related issues / PRs ❤️ ), @bradintheusa can you review this and if all good we can merge in, if there's anything else needed before next release then we can add that in too.

Perhaps it would be good to co-ordinate a plan of action going forward on what needs addressing next, what do you two think?

**Comment by bradintheusa** [comment]
Sounds like a good plan to me.

**Comment by bradintheusa** [comment]
Looks good, there's a space missing at the end of the error. But we can patch that. 

```
Cannot not find minSdk from android/app/build.gradle or android/local.propertiesSpecify minSdk in either android/app/build.gradle or android/local.properties  
```

**Comment by bradintheusa** [comment]
I'm quite ok to keep on top of the issues and provide support. I can also update the documentation/examples as needed.

**Comment by MarkOSullivan94** [comment]
Thanks for reviewing @bradintheusa, I've merged in now.

Anything either of you two @RatakondalaArun or @bradintheusa want to include before new version is released?

**Comment by RatakondalaArun** [comment]
I think we can fix #350 as well

**Comment by bradintheusa** [comment]
Agreed with #350 then it would be nice to push a version out to show some activity.

**Comment by bradintheusa** [comment]
After the release, I can triage the open issues and remaining PR.

**Comment by MarkOSullivan94** [comment]
I've opened a PR to fix #350 - https://github.com/fluttercommunity/flutter_launcher_icons/pull/364

Going forward it might be nice to adopt [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) - I know [Melos](https://melos.invertase.dev/) has a tool which automatically generates changelogs if conventional commits are used

I've also given @RatakondalaArun write access to the repo and @bradintheusa triage access, Brad if you are wanting write access then I can increase the access.

**Comment by MarkOSullivan94** [comment]
Thank you @RatakondalaArun and @bradintheusa for your reviews and contributions, thanks to you both `v0.9.3` is now published 🎉

**Comment by RatakondalaArun** [comment]
@MarkOSullivan94 I am wondering how is the package deployment happening? I don't see any CD pipeline in place

**Comment by MarkOSullivan94** [comment]
> @MarkOSullivan94 I am wondering how is the package deployment happening? I don't see any CD pipeline in place

Right now there's no CD in place @RatakondalaArun, whenever a new version is needing to be published, I run the [publish command](https://dart.dev/tools/pub/cmd/pub-lish) on my local terminal.

It's not something I had considered doing in the past but [looking at this blog post](https://www.bradcypert.com/dart-packages-with-github-actions/) it seems that we could trigger a new release to be published to pub whenever a new tag starting with `v` is created which would reduce the manual effort required to get new versions shipped and especially useful during times weren't it's hard to reach me.

**Comment by RatakondalaArun** [comment]
Hi @MarkOSullivan94 and @bradintheusa 

I think it would be very helpful if we start implementing support for stable platforms MacOS, Windows, Linux, and Web.
We do already have PR's for most of the platforms except Linux.

**MacOS:**
- #255 (conflicts)
- #189 (conflicts)

**Windows:**
- #255 (conflicts)
- #189 (conflicts)

**Linux:**
- No PR's

**Web:**
- #189 (conflicts)

What you guys think?

**Comment by bradintheusa** [comment]
!00% agree. It seems like it would be easy & popular.

**Comment by RatakondalaArun** [comment]
Hi @MarkOSullivan94, @bradintheusa 

I am thinking about restructuring flutter_icons_config.yaml format

current config
```yaml
flutter_icons:
  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/icon-710x599-android.png"
  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  # if I add support for web
  web: true
  image_path_web: "path/to/web.png"
  background_color_web: "#hexcolor"
  theme_color_web: "#hexcolor"
  # if we add support for linux
  linux true
  image_path_linux: "path/to/image.png"
  #if we add support for windows
  windows: true
  image_path_windows: true
  # ... and so on with other platforms
```

My suggestion

```yaml
image_path: "path/to/image.png" # fallback if not specified for platform
android:
  generate: true # specifies weather to generate icons for this platform or not
  image_path: "path/to/image.png"
  adaptive_icon_background: "path/to/image.png"
  adaptive_icon_foreground: "path/to/image.png"
ios:
  generate: true
  image_path: "path/to/image.png"
web:
  generate: true
  image_path: "path/to/image.png"
  background_color: "#hexcode"
  theme_color: "#hexcode"
linux:
  generate: true
  image_path: "path/to/image.png"
windows:
  generate: true
  image_path: "path/to/image.png"
macos:
 generate: true
 image_path: "path/to/image.png"
```
What this will bring to the table?
- better organized configs
- easy to maintain
- we can also use [checked_yaml](https://pub.dev/packages/checked_yaml) to add static support

Let me know what you guys think
