### ISSUE TITLE
Dark Mode iOS always launches splash screen as red before going dark colour [BUG] 

### ISSUE THREAD

**Issue by haydgately** [fluttercommunity/flutter_launcher_icons#370]
### :information_source: Info

Version: 2.2.3+1

### :speech_balloon: Description

Dark Mode iOS always launches splash screen as red before going dark colour 

### :scroll: Pubspec.yaml

```
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/images/icon.png
  android: true
  ios: true
```

In Main: 
```
void main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  final savedThemeMode = await AdaptiveTheme.getThemeMode();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // FirebaseCrashlytics.instance.crash();
  runApp(
    EasyLocalization(
      supportedLocales: [Locale('en'), Locale('fr')],
      path: 'assets/translations', // <-- change the path of the translation files
      fallbackLocale: Locale('en', 'GB'),
      child: MyApp(savedThemeMode: savedThemeMode),
    ),
  );
  FlutterNativeSplash.remove();
}
```
