### ISSUE TITLE
[BUG] minSdk not found

### ISSUE THREAD

**Issue by Abdulkader-Safi** [fluttercommunity/flutter_launcher_icons#384]
### :information_source: Info
Version: `e.g. v0.9.3`

### :speech_balloon: Description
Hi there,
I got problem when I run command 
flutter pub run flutter_launcher_icons:main 
in the terminal after command
flutter pub get

the output 
```log
════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.9.3)                               
  ════════════════════════════════════════════
  

✓ Successfully generated launcher icons
Unhandled exception:

✗ ERROR: InvalidConfigException 
Cannot not find minSdk from android/app/build.gradle or android/local.propertiesSpecify minSdk in either android/app/build.gradle or android/local.properties
#0      createIconsFromConfig (package:flutter_launcher_icons/main.dart:96:7)
#1      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
#2      main (file:///home/abdulkader/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.3/bin/main.dart:7:26)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

### :scroll: Pubspec.yaml
```yaml
name: note_taking_application
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path: ^1.8.1
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
```
