### ISSUE TITLE
[BUG] Run package failed

### ISSUE THREAD

**Issue by lsaudon** [fluttercommunity/flutter_launcher_icons#417]
### :information_source: Info

Version: `v0.10.0`

### :speech_balloon: Description

When I run this command `flutter pub run flutter_launcher_icons`
I have this error `Could not find bin\flutter_launcher_icons.dart in package flutter_launcher_icons.`

### :scroll: Pubspec.yaml

```yaml
name: my_project
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
```

### :scroll: Doctor

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.22000.918], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2021.1)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by RatakondalaArun** [comment]
Hi @lsaudon 

This feature is not yet released to pub.dev. For the time being you need to use `flutter pub run flutter_launcher_icons:main`

In case you need the latest one you need to add flutter_launcher_icons as git dependency

```yaml
pubspec.yaml

dependencies:
  flutter_launcher_icons:
    git: https://github.com/fluttercommunity/flutter_launcher_icons
    branch: master
```
