### ISSUE TITLE
Cannot Open file

### ISSUE THREAD

**Issue by muthiks** [fluttercommunity/flutter_launcher_icons#418]
How do i fix this error?? Could not generate launcher icons

```log
FileSystemException: Cannot open file, path = 'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png' (OS Error: The system cannot find the path specified.
```

This is my configuration>
```yaml
flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
```
