### ISSUE TITLE
[BUG] The file xxx.png for the image set "AppIcon" does not exist

### ISSUE THREAD

**Issue by jtaxiexpress** [fluttercommunity/flutter_launcher_icons#437]
### :information_source: Info
```
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

```
### Flutter doctor
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-arm, locale ja-JP)
    • Flutter version 3.3.8 on channel stable at /Users/t/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (11 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/t/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3
```
