### ISSUE TITLE
Cannot rename file (OS Error: The system cannot find the file specified) [BUG] 

### ISSUE THREAD

**Issue by Dev-Akash** [fluttercommunity/flutter_launcher_icons#440]
### :information_source: Info

Version: `e.g. v0.9.3`

### :speech_balloon: Description

While changing icon came across following error

> flutter pub run flutter_launcher_icons:main -f config/icon_flutter_launcher_icons.yaml
Unhandled exception:
FileSystemException: Cannot open file, path = '.\.dart_tool/pub\incremental\flutter_launcher_icons\tmpd4b83769\main.dart.incremental.dill.incremental.dill' (OS Error: The system cannot find the path specified., errno = 3)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension> Cannot rename file to '.\.dart_tool/pub\bin\flutter_launcher_icons\main.dart-2.18.5.snapshot', path = '.\.dart_tool/pub\incremental\flutter_launcher_icons\tmpd4b83769\main.dart.incrementa
l.dill.incremental.dill' (OS Error: The system cannot find the file specified.
, errno = 2)
pub finished with exit code 66

### :scroll: Pubspec.yaml

```
version: 2.2.1+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # GET
  get: 4.6.5
  get_storage: 2.0.3
  # DIO
  dio: 4.0.6
  dio_http_cache: 0.3.0
  # FONT
  google_fonts: 3.0.1
  auto_size_text: 3.0.0
  #IMAGES, SLIDERS, LAYOUTS
  cached_network_image: 3.2.1
  carousel_slider: 4.1.1
  flutter_svg: 1.1.1+1
  image_picker: 0.8.5+3
  cupertino_icons: any
  shimmer: 2.0.0
  intl_phone_field: 3.1.0
  # WEB
  webview_flutter: 3.0.4
  flutter_html: 3.0.0-alpha.3
  url_launcher: 6.1.5
  # FIREBASE
  firebase_messaging: 12.0.1
  cloud_firestore: 3.4.0
  firebase_auth: 3.5.0
  firebase_core: 1.20.0
  firebase_storage: 10.3.3
  # GOOGLE MAPS
  google_maps_flutter: 2.1.9
  map_launcher: 2.2.3
  google_maps_place_picker_mb:
    git:
      url: https://github.com/SmarterVision/google_maps_place_picker_mb.git
      ref: 2.0.0-mb.20
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.3
  change_app_package_name: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config/
    - assets/img/
    - assets/icon/
```
