### ISSUE TITLE
[BUG] Android Adaptive Icons Not Generated

### ISSUE THREAD

**Issue by FrBernad** [fluttercommunity/flutter_launcher_icons#448]
### :information_source: Info

Version: `e.g. v^0.11.0`

### :speech_balloon: Description

The adaptive icons are not being generated inside the mipmap folders using a valid adaptive configuration.

### :scroll: Pubspec.yaml

```
flutter_icons:
  image_path_android: "assets/images/launcher_icon_text_only.png"

  android: true
  adaptive_icon_foreround: "assets/images/launcher_icon_fg.png"
  adaptive_icon_background: "assets/images/launcher_icon_bg.png"
  min_sdk_android: 16

  ios: true
  remove_alpha_ios: true
```
