### ISSUE TITLE
Can't use with Dart 2.1.0 because of dart_config dependency

### ISSUE THREAD

**Issue by v3rm0n** [fluttercommunity/flutter_launcher_icons#45]
I opened a PR on **dart_config** to fix this https://github.com/chrisbu/dart_config/pull/12

**Comment by dooboolab** [comment]
This is really critical. I can't make the build..

**Comment by v3rm0n** [comment]
For a quick fix you can try adding
```
dependency_overrides:
  dart_config:
    # https://github.com/chrisbu/dart_config/pull/12
    git:
      url: git@github.com:v3rm0n/dart_config.git
      ref: v3rm0n-patch-1
```
To your pubspec.yaml

**Comment by galinowski** [comment]
Thanks for sharing the fix, however I'm getting "Host key verification failed. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists."

**Comment by v3rm0n** [comment]
Strange, you could also try to just fork my repo and use that instead.

**Comment by SPodjasek** [comment]
I had to modify this even further to make `flutter_launcher_icons` work.

So if you run into some errors like this:

> Error: The parameter 'path' of the method 'ConfigFilesystemLoader::loadConfig' has type dart.core::String, which does not match the corresponding type in the overridden method (dynamic).

use this:

```
dependency_overrides:
  dart_config:
    git:
      url: https://github.com/SPodjasek/dart_config.git
      ref: fix_dart21
```
