### ISSUE TITLE
iOS Launcher Icon background always black

### ISSUE THREAD

**Issue by chitgoks** [fluttercommunity/flutter_launcher_icons#454]
Hi i wish to ask what is missing. I have no problems with the android icons. im trying to generate ios icons but the background is always black. the imagehas a transparent background. now i read that it should be opaque in ios. so i added the image_path_ios but it doesnt work

what am i missing here

```
flutter_icons:
  ios: true
  android: true
  image_path: 'assets/launcher_icon.png'
  image_path_ios: 'assets/launcher_icon_ios.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/launcher_icon.png'

```
