### ISSUE TITLE
THIS IS SO ANNOYING[BUG] 

### ISSUE THREAD

**Issue by Princewil** [fluttercommunity/flutter_launcher_icons#459]
![Screenshot (3)](https://user-images.githubusercontent.com/40724883/218926176-933e9529-5325-4bf7-b787-fce385474c28.png)

I Have been having this issue for more than two hours, please what am I missing?
Can someone help me?

**Comment by MrMineToons** [comment]
Hello!

Instead
```
flutter_icon:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
```

Do:
```
flutter_icons:  <-- Caution here...
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
```
