### ISSUE TITLE
Version 0.12.0 ignores remove_alpha_ios setting

### ISSUE THREAD

**Issue by dvorapa** [fluttercommunity/flutter_launcher_icons#462]
### :information_source: Info

Version: `v0.12.0`

### :speech_balloon: Description

I upgraded to 0.12.0, but it broke all my icons suddenly, because remove_alpha_ios option in pubspec.yaml gets ignored now.  You can see that in this respose:
```
$ flutter pub run flutter_launcher_icons
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.12.0)                               
  ════════════════════════════════════════════
  
• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon

WARNING: Icons with alpha channel are not allowed in the Apple App Store.
Set "remove_alpha_ios: true" to remove it.

• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...
⚠️Requirements failed for platform Web. Skipped
Creating Icons for Windows...
⚠️Windows config is not provided or windows.generate is false. Skipped...
⚠️Requirements failed for platform Windows. Skipped
Creating Icons for MacOS...
⚠️Requirements failed for platform MacOS. Skipped

✓ Successfully generated launcher icons
```

### :scroll: Pubspec.yaml

```
name: stepslow
description: Simple Music Player for Dancers
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.2.5+7
homepage: https://www.dvorapa.cz

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^3.0.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  audioplayers: ^3.0.1
  on_audio_query: ^2.6.1
  flutter_beep: ^1.0.0
  wakelock: '>=0.6.2 <1.0.0'
  collection: ^1.17.0
  volume_regulator: ^2.1.0
  easy_dialogs: ^2.0.0
  typicons_flutter: '>=0.5.0 <1.0.0'
  shared_preferences: ^2.0.18
  yaml: ^3.1.1
  ffmpeg_kit_flutter: 5.1.0-LTS
  permission_handler: ^10.2.0
  path_provider: ^2.0.13
  about: ^2.1.1
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_launcher_icons: '>=0.12.0 <1.0.0'
  pubspec_extract: ^2.0.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - CHANGELOG.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

**Comment by AntonLT** [comment]
Same issue

**Comment by tnaseem** [comment]
I'm also experiencing the same issue. App Store Connect is complaining that the alpha channel is still there.

My pubspec.y'all snippet:


```
flutter_icons:
  android: true
  ios: true
  web: false
  remove_alpha_ios: true
  image_path: 'assets/images/app/app_icon.png'
```

**Comment by mike-500** [comment]
I submitted PR #464 to fix this. 
If you want to test it, use it in your pubspec.yaml like so:
`dev_dependencies:
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: 26fedcee4b0e6f7a85f65f1fb48834a21f57e970`

**Comment by itwondersteam** [comment]
> I submitted PR #464 to fix this. If you want to test it, use it in your pubspec.yaml like so:
> 
> ```
> dev_dependencies:
>   flutter_launcher_icons:
>     git:
>       url: https://github.com/fluttercommunity/flutter_launcher_icons.git
>       ref: 26fedcee4b0e6f7a85f65f1fb48834a21f57e970
> ```

Have tested this and the warning get cleared.

**Comment by CodingwithTea** [comment]
> > I submitted PR #464 to fix this. If you want to test it, use it in your pubspec.yaml like so:
> > ```
> > dev_dependencies:
> >   flutter_launcher_icons:
> >     git:
> >       url: https://github.com/fluttercommunity/flutter_launcher_icons.git
> >       ref: 26fedcee4b0e6f7a85f65f1fb48834a21f57e970
> > ```
> 
> Have tested this and the warning get cleared.

No working. Still getting the same warning. Can anyone help?

**Comment by OutdatedGuy** [comment]
@MarkOSullivan94, this issue has been resolved. Can you close it?

**Comment by iatndiag** [comment]
ver. 0.13.1 and (latest vers. of A.S., latest SDK)
With all "... config.g" files:

The imported library 'package:flutter_launcher_icons/config/macos_config.g.dart' can't have a part-of directive. (Documentation)  Try importing the library that the part is a part of.

**Comment by inamhwebelight** [comment]
it is working fine with this code 
```
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon/logo-admin.png"
  remove_alpha_ios: true
```

`  flutter_launcher_icons: ^0.13.1`
