### ISSUE TITLE
[BUG] MacOS icons not rounded

### ISSUE THREAD

**Issue by Wizzel1** [fluttercommunity/flutter_launcher_icons#463]
### :information_source: Info

Version: `v0.12.0`

### :speech_balloon: Description

Are we supposed to use an image that already has a border-radius in order to generate a rounded app-icon for MacOS?

### :scroll: Pubspec.yaml

```yaml
name: test_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_riverpod: ^2.2.0
  supabase_flutter: ^1.4.1
  multiple_result: ^4.0.0
  uuid: ^3.0.7
  easy_debounce: ^2.0.3
  go_router: ^6.2.0
  sentry_flutter: ^6.20.1
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.1
  flutter_layout_grid: ^2.0.1
  file_picker: ^5.2.5
  extended_image: ^7.0.1
  syncfusion_flutter_datepicker: ^20.4.51
  package_info_plus: ^3.0.3
  flutter_reorderable_list: ^1.2.0
  flutter_staggered_animations: ^1.1.1
  toggle_switch: ^2.0.1
  riverpod_annotation: ^1.1.1
  just_the_tooltip: ^0.0.12
  fl_chart: ^0.61.0
  syncfusion_flutter_datagrid: ^20.4.51
  animated_flip_counter: ^0.2.5
  flutter_colorpicker: ^1.0.3
  email_validator: ^2.1.17
  puppeteer: ^2.22.0
  path_provider: ^2.0.13
  csv: ^5.0.1
  intl: ^0.18.0
  recase: ^4.1.0
  dyn_mouse_scroll:
    git:
      url: https://github.com/Wizzel1/dyn_mouse_scroll
      ref: main
  openai_gpt3_api:
    git: https://github.com/morriskurz/openai_gpt3_dart_api
  deepl_dart: ^1.2.0
  bitsdojo_window: ^0.1.5
  envied: ^0.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_animate: ^4.1.0
  timezone: ^0.9.1

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  riverpod_generator: ^1.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_bg.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - google_fonts/
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
