### ISSUE TITLE
[BUG] Doesn't work with the flavors on the very_good create app template

### ISSUE THREAD

**Issue by aalex** [fluttercommunity/flutter_launcher_icons#466]
### :information_source: Info

Version: `0.12.0`

### :speech_balloon: Description

I am trying to set up some app icons, but I don’t see the right icons. We started from a `very_good create` app template, and then added some icons with `flutter_launcher_icons`, but the default icons from the `very_good` app template were not replaced by the ones generated by `flutter_launcher_icons`. How can we fix this? Here is a minimal prototype that reproduces the bug, and a but ticket that describes it, including all the technical details: https://github.com/artpluscodeinc/proto_very_good_flavor_icons/issues/1 

### :scroll: Pubspec.yaml

```
name: proto_very_good_flavor_icons
description: Prototype that allows to create custom application icons according to the flavor.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
```
