### ISSUE TITLE
Fails with unhandled exception NoSuchMethodError: Attempted to use type 'MapEntry' as a function

### ISSUE THREAD

**Issue by sanjul** [fluttercommunity/flutter_launcher_icons#47]
Have this configuration in pubspec : 

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.6.1"

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icons/appIcon.png"
```

It fails with following error on running **flutter pub pub run flutter_launcher_icons:main**

```
NoSuchMethodError: Attempted to use type 'MapEntry' as a function. Since types do not define a method 'call', this is no
t possible. Did you intend to call the MapEntry constructor and forget the 'new' operator?
Receiver: MapEntry
Tried calling: MapEntry("dependencies", Instance of 'YamlMap')
#0      loadConfigFile (package:flutter_launcher_icons/main.dart:37:16)
<asynchronous suspension>
#1      createIcons (package:flutter_launcher_icons/main.dart:8:3)
<asynchronous suspension>
#2      main (file:///D:/no-backup/stack/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.6.1/bin/mai
n.dart:5:3)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
pub finished with exit code 255
```

Please have a look
