### ISSUE TITLE
Message printed which states icons are being generated for MacOS, Windows and Web despite not being in config

### ISSUE THREAD

**Issue by MarkOSullivan94** [fluttercommunity/flutter_launcher_icons#476]
### :information_source: Info

Version: `v0.13.0`

### :speech_balloon: Description

When there is no configuration for MacOS, Windows or Web in the yaml, we still see output in the console which suggests icons were being generated for all 3.

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

```yaml
flutter_icons:
  android: true
  ios: false
  image_path: "assets/launcher_icon/agent.png"
```
