### ISSUE TITLE
Improve flavor support

### ISSUE THREAD

**Issue by tmura-ido** [fluttercommunity/flutter_launcher_icons#490]
### :speech_balloon: Description
In the current version 0.13.1 there is a way to spread the icons to its flavor folder with the yaml naming scheme, but it only works if the yaml file is in the **root** folder and that is an inconvenience.
I have a lot of flavors for one project and I want to make some order in it, so I want my launcher icons config files to be inside my organized folders, but when i use them with a the flavor naming scheme, it doesn't put the images in the correct flavor folder, it puts them inside the main folder.

Maybe it should be an attribute by itself, `flavor` like so:
```
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "not_assets/flavor_name/logo.png"

  flavor: flavor_name
```

### :question: Platform
All platforms
