### ISSUE TITLE
[BUG] Green border when setting background_color_ios

### ISSUE THREAD

**Issue by fotiDim** [fluttercommunity/flutter_launcher_icons#514]
### :information_source: Info

Version: `0.13.1`

### :speech_balloon: Description

When I set `background_color_ios` to any color other than white, I am getting a green border around my icon.

### :scroll: Pubspec.yaml
```
flutter_icons:
  image_path: assets/icon/icon_transparent.png
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#26262D"
  android: true
  adaptive_icon_foreground: assets/icon/adaptive_icon.png
  adaptive_icon_background: "#26262D"
```

![Screenshot 2023-09-19 at 10 44 08](https://github.com/fluttercommunity/flutter_launcher_icons/assets/2326415/9de8a964-a593-40ea-aa75-be7546283f79)
![Screenshot 2023-09-19 at 10 43 16](https://github.com/fluttercommunity/flutter_launcher_icons/assets/2326415/69ff0f24-211d-455f-a829-63e55b2b7d06)

![Screenshot 2023-09-19 at 10 46 03](https://github.com/fluttercommunity/flutter_launcher_icons/assets/2326415/b50cdb6c-c12b-4bbf-a0dd-42830131de61)
