### ISSUE TITLE
flutter_icons has been deprecated please use flutter_launcher_icons instead in your yaml files

### ISSUE THREAD

**Issue by santo122** [fluttercommunity/flutter_launcher_icons#517]
admin@MAC-RT-04 r-pay-app % flutter pub run flutter_launcher_icons -f pubsoec.yaml
Deprecated. Use `dart run` instead.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)                               
  ════════════════════════════════════════════
  

⚠ Warning: flutter_icons has been deprecated please use flutter_launcher_icons instead in your yaml files
• Creating default icons Android
• Adding a new Android launcher icon

WARNING: Icons with alpha channel are not allowed in the Apple App Store.
Set "remove_alpha_ios: true" to remove it.

• Overwriting default iOS launcher icon with new icon
No platform provided

✓ Successfully generated launcher icons

**Comment by mundadapurva** [comment]
I would like to work on this one. Please assign me this issue.

**Comment by pumano** [comment]
you use old 

`flutter_icons:`

inside pubspec

when you change to:

`flutter_launcher_icons:`

error has gone

**Comment by cyberpwnn** [comment]
It doesnt go away

**Comment by Katekko** [comment]
@cyberpwnn you are thinking the line that you need to change is in dependencies, but its in under this.

Here:
```YAML
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"
  remove_alpha_ios: true
```
  
 Your is probably like this one above, just change to 
 
```YAML
 flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"
  remove_alpha_ios: true
```
