### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lcsvcn** [fluttercommunity/flutter_launcher_icons#528]
### :information_source: Info

Version: `v0.13.1`

### :speech_balloon: Description

7 unnecessary icons being generated for iOS. 

<img width="761" alt="Screenshot 2023-10-18 at 16 22 20" src="https://github.com/fluttercommunity/flutter_launcher_icons/assets/6011385/12ae9b8e-518d-4346-8d6a-0258c3826006">

<img width="776" alt="Screenshot 2023-10-18 at 16 23 38" src="https://github.com/fluttercommunity/flutter_launcher_icons/assets/6011385/eb3f926b-a77d-4000-b412-cbc669364a85">

### :scroll: Pubspec.yaml

```
flutter_icons:
  ios: true
  android: true
  image_path: 'assets/launcher/icon.png'
  min_sdk_android: 19
  adaptive_icon_background: '#fff'
  adaptive_icon_foreground: 'assets/launcher/foreground.png'
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/launcher/foreground.png'
    background_color: '#fff'
    theme_color: '#fff'
  windows:
    generate: true
    image_path: 'assets/launcher/icon.png'
  macos:
    generate: true
    image_path: 'assets/launcher/icon.png'
```

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect
