### ISSUE TITLE
[BUG] MacOS logo does not change

### ISSUE THREAD

**Issue by RoyalScribblz** [fluttercommunity/flutter_launcher_icons#532]
### :information_source: Info
Version: v0.13.1
OS: MacOS Ventura 13.6 (22G120)
Model: MacBook Air M1 2020

### :speech_balloon: Description
The icons produced are correct as far as I am aware and you can see them in each folder, but when I run it on MacOS it just shows the default icon. I tested it on Chrome (web) and it show the logo I set as expected.
![image](https://github.com/fluttercommunity/flutter_launcher_icons/assets/36082342/a6d6d841-a5dc-4ee3-93bd-2c7c0ac08942) 

### :scroll: Pubspec.yaml
```
flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  ios: true
  remove_alpha_ios: true
  android: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
```

### :desktop_computer: Output
```
Building package executable... (1.4s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...              done
Creating Icons for Windows...          done
Creating Icons for MacOS...            done

✓ Successfully generated launcher icons

```
