### ISSUE TITLE
Flavors?

### ISSUE THREAD

**Issue by GregorySech** [fluttercommunity/flutter_launcher_icons#54]
It would be nice to have the possibility to use this package also to manage various flavors icons, I guess this might be a breaking change to simply replicate this configuration API.
Another option would be making a new package, some type of flavors helper which uses this package to handle the icon parts.

**Comment by GregorySech** [comment]
It might not be a breaking change, just adding a "flavors" node with all the flavors icons which replicates the configuration might do the trick.

**Comment by MarkOSullivan94** [comment]
I'm not sure I understand where you're coming from.

I did a bit of research and I've found it's possible to have a debug icon and a release icon for Android: https://stackoverflow.com/questions/22875948/how-to-provide-different-android-app-icons-for-different-gradle-buildtypes/22876224#22876224

Are you wanting something like that? Where you can specify a debug flavor?

Or are you just wanting an option to quickly switch between different flavors of launcher icons? 

If you do, this is already possible, you could have your image_path and android / ios icon names all specified for the different flavours and then just comment out the ones which you don't want to use. It'll quickly switch between them for you.

**Comment by MarkOSullivan94** [comment]
Unfortunately unless Flutter cmd line tools support that, you wont be able to run `flutter build --flavor <flavor>`.

I'll also need to look into how passing cmd line arguments will work as I haven't done that before.

Curious how you would prefer this to be setup within the pubspec.yaml config?

**Comment by GregorySech** [comment]
The flutter CLI supports it. It's just a pass through to gradle flavours and to iOS schemas. 
I'm reproducing these articles about flavoring right now:
 - From salvatoregiordanoo at Medium : [article1](https://medium.com/@salvatoregiordanoo/flavoring-flutter-392aaa875f36)
- From Natalie Masse Hooper at Cogitas : [article2](https://cogitas.net/creating-flavors-of-a-flutter-app/)

I guess a good idea might be, while taking as base the readme example:
```
dev_dependencies: 
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: "^0.6.1"
  
flutter_icons:
  android: true 
  ios: "Example-Icon"
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon_android.png"
  image_path_ios: "assets/icon/icon_ios.png"
  adaptive_icon_background: "#FFFAFAFA"
  adaptive_icon_foreground: "assets/icon/icon-foreground.png"
  flavors:
    <flavor-name>:
      android: true 
      ios: "<icon name>"
      image_path: "<path here>"
      image_path_android: "<path here>"
      image_path_ios: "<path here>"
      adaptive_icon_background: "<color here>"
      adaptive_icon_foreground: "<path here>"
```
