### ISSUE TITLE
[BUG] Backround color not changing

### ISSUE THREAD

**Issue by md-rifatkhan** [fluttercommunity/flutter_launcher_icons#553]
Background Color Not Changing on **Android 14 Emulator**

Screenshot: 
![image](https://github.com/fluttercommunity/flutter_launcher_icons/assets/102645154/06167793-4f08-443d-9ce7-7be378c44f6e)

```
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/play_store_512.png"

  android: "launcher_icon"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#1f1d1e"
  daptive_icon_foreground: "assets/play_store_512.png"

  ios: true
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true

  web:
    generate: true
    image_path: "assets/play_store_512.png"
    background_color: "#1f1d1e"
    theme_color: "#1f1d1e"

  windows:
    generate: true
    image_path: "assets/play_store_512.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: false
    image_path: "assets/play_store_512.png"

```
