### ISSUE TITLE
[BUG] icon resolution decreased

### ISSUE THREAD

**Issue by LeoManzini** [fluttercommunity/flutter_launcher_icons#556]
### :information_source: Info

Version: `0.13.1`

### :speech_balloon: Description

After using the dependency to change my app icon, I noticed a blur in the compiled app icon, as if the icon resolution had decreased on the phone. Could this be due to my selected image or something similar? Perhaps related to the image quality?

### :scroll: Pubspec.yaml

```yaml
name: dev_bank
description: "Mobile Flutter app for a development bank."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo-icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/foreground-logo-icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
```

Also the images used:

<details><summary>logo-icon</summary>

    ![logo-icon](https://github.com/fluttercommunity/flutter_launcher_icons/assets/39606289/1e4f786c-a7c1-4aaa-ad8b-020f56be6bfc)

</details>

<details><summary>foreground-logo-icon</summary>

    ![foreground-logo-icon](https://github.com/fluttercommunity/flutter_launcher_icons/assets/39606289/38963ed3-f25b-4f3a-a8d5-79083933b672)

</details>
