### ISSUE TITLE
[BUG] Android icon is zoomed in

### ISSUE THREAD

**Issue by muezz** [fluttercommunity/flutter_launcher_icons#557]
### :information_source: Info
Version: `v0.13.1`

### :speech_balloon: Description
On iOS, the icons are generated correctly and look okay as well. Somehow, on android, the icons are too zoomed in even though the source is the same for both. 
<img width="438" alt="image" src="https://github.com/fluttercommunity/flutter_launcher_icons/assets/100420605/57dd98c4-33d0-49ff-b4b6-31f4b77f2a5e">
<img width="435" alt="image" src="https://github.com/fluttercommunity/flutter_launcher_icons/assets/100420605/bde8de16-fc21-4e5d-b36a-3f761e185f1c">
<img width="455" alt="image" src="https://github.com/fluttercommunity/flutter_launcher_icons/assets/100420605/7501a3a1-c3e0-4efb-839b-f8dde9449fb2">

### :scroll: Pubspec.yaml
```yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/iuhabit-1.png"
  min_sdk_android: 21
  # adaptive_icon_background: "#1F1D2B"
  # adaptive_icon_foreground: "assets/logos/iuhabit-1.png"
```
