### ISSUE TITLE
Because flutter_launcher_icons >=0.4.0 <0.6.1 depends on dart_config >=0.3.0+1 which requires SDK version <2.0.0, flutter_launcher_icons >=0.4.0 <0.6.1 is forbidden. So, because mbf depends on flutter_launcher_icons 0.6.0, version solving failed.

### ISSUE THREAD

**Issue by nausharipov** [fluttercommunity/flutter_launcher_icons#56]
When I try to run the app, this error comes up:
Because flutter_launcher_icons >=0.4.0 <0.6.1 depends on dart_config >=0.3.0+1 which requires SDK version <2.0.0, flutter_launcher_icons >=0.4.0 <0.6.1 is forbidden. So, because mbf depends on flutter_launcher_icons 0.6.0, version solving failed.

My pubspec.yaml file:
 ```
 flutter_launcher_icons: "0.5.2"
  flutter_icons:
    image_path: "assets/icon/logo.png"
    android: true
    ios: true
    adaptive_icon_background: "#090909"
    adaptive_icon_foreground: "assets/icon/logo.png"
```

**Comment by MarkOSullivan94** [comment]
Please update to the latest version of the package. The latest version of the package uses a forked version of dart_config which allows me to ensure it'll always run with my forked version.

```
flutter_launcher_icons: "0.6.1"
flutter_icons:
   image_path: "assets/icon/logo.png"
   android: true
   ios: true
   adaptive_icon_background: "#090909"
   adaptive_icon_foreground: "assets/icon/logo.png"
```

This is what your config should look like
