### ISSUE TITLE
[BUG] App icon generation with flavors seems to corrupt project.pbxproj

### ISSUE THREAD

**Issue by LennardDeurman** [fluttercommunity/flutter_launcher_icons#565]
### :information_source: Info

Version: `0.13.1`

### :speech_balloon: Description

Using the flutter_launcher_icons package I'm trying to create App icons for two flavors. I've created a flutter_launcher_icons-production.yaml and a flutter_launcher_icons-staging.yaml. My two flavors are named production and staging. 

After running the command: `flutter pub run flutter_launcher_icons` I receive an error when opening the Xcode project, and get the following error when running the app again:

![Screenshot 2024-07-08 at 10 34 54](https://github.com/fluttercommunity/flutter_launcher_icons/assets/18402457/bed8769b-b39e-40d8-8485-de99e9570157)
![Screenshot 2024-07-08 at 10 35 55](https://github.com/fluttercommunity/flutter_launcher_icons/assets/18402457/c70689b9-1cc0-4420-b1a4-01697e7d1e12)

When I reset the project.pbxproj to the version before the modifications after the icon generations it works, and I can manually select the icons. It would however be great if this can be automatically done. 

### :scroll: Pubspec.yaml

flutter_launcher_icons-production.yaml

```
flutter_launcher_icons:
  android: true
  adaptive_icon_background: "assets/launcher/production/android/background.png"
  adaptive_icon_foreground: "assets/launcher/production/android/foreground.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/production/icon.png"
```

flutter_launcher_icons-staging.yaml

```
flutter_launcher_icons:
  android: true
  adaptive_icon_background: "assets/launcher/staging/android/background.png"
  adaptive_icon_foreground: "assets/launcher/staging/android/foreground.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/staging/icon.png"
```
