### ISSUE TITLE
Cannot generate only for ios

### ISSUE THREAD

**Issue by alextekartik** [fluttercommunity/flutter_launcher_icons#57]
Thanks for the package. I try to generate icon only for iOS (latest version so I guess 0.6.1) with the following configuration

```yaml
flutter_icons:
  android: false
  ios: true
  image_path_ios: "assets/dev/icon/ios_app_icon_1024x1024.png"
```

running

    flutter pub pub run flutter_launcher_icons:main

complain with the error

    Missing 'image_path' or 'image_path_android + image_path_ios' within configuration

And if I do add an image_path, it seems the `android: false` flag is ignore and my android icons are overriden
