### ISSUE TITLE
[BUG] Android: Black app launcher icon

### ISSUE THREAD

**Issue by Navid-Rahman** [fluttercommunity/flutter_launcher_icons#578]
I'm using `flutter_launcher_icons` v0.14.0 to generate app icons for both Android and iOS. Despite providing a colored logo, the generated app icons are black in Android. But in iOS this is working fine. 
The logo is correctly formatted as a PNG file, and I've set the necessary configuration in `pubspec.yaml`, but the output remains incorrect.

```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
```

**Flutter Doctor result:**  
<img width="677" alt="Screenshot 2024-09-22 at 1 37 04 PM" src="https://github.com/user-attachments/assets/845a86e8-9ae2-4481-a536-b16893dc98b5">

Do you know if this is a bug from the latest update? Or am I doing something wrong?
