### ISSUE TITLE
I'm having a problem change my launcher icon.

### ISSUE THREAD

**Issue by Ebenezerkifle** [fluttercommunity/flutter_launcher_icons#583]
### :information_source: Info
flutter_launcher_icons: ^0.13.1

### :speech_balloon: Description
Building package executable... 
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android

✕ Could not generate launcher icons
PathNotFoundException: Cannot open file, path = 'assets/icon/icon.png' (OS Error: No such file or directory, errno = 2)

### :scroll: Pubspec.yaml

```yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo_icon.jpg"
  remove_alpha_ios: true
```
