### ISSUE TITLE
Seperate AppIcon-Tinted folder is not needed.

### ISSUE THREAD

**Issue by frankmer** [fluttercommunity/flutter_launcher_icons#587]
### :information_source: Info
flutter_launcher_icons: v0.14.1

### :speech_balloon: Description
When i am generate the icons "flutter_launcher_icons" 2 folders "AppIcon" and "AppIcon-Tinted". My Xcode (v16.0) expect all images in the same folder.  When i set in Xcode "Appearances" to "Any, Dark, Tinted" then move the images to the "AppIcon" folder and delete the "AppIcon-Tinted" folder it works perfectly.

### :scroll: Pubspec.yaml
  flutter_launcher_icons: ^0.14.0

```yaml
flutter_launcher_icons:
  ios: true
  image_path_ios: "appicon-ios.png"
  image_path_ios_tinted_grayscale: "appicon-ios-monochrome.png"
```
