### ISSUE TITLE
Cannot open file, path = 'assets/icon/icon.png' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by aibekdv** [fluttercommunity/flutter_launcher_icons#588]
### :information_source: Info

Cannot open file, path = 'assets/icon/icon.png' (OS Error: No such file or directory, errno = 2)

### :speech_balloon: Description

```dart run flutter_launcher_icons ```

Building package executable... 
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.14.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android

✕ Could not generate launcher icons
PathNotFoundException: Cannot open file, path = 'assets/icon/icon.png' (OS Error: No such file or directory, errno = 2)

### :scroll: Pubspec.yaml

```yaml
assets:
    - assets/images/.
    - assets/icons/.
    - assets/icons/logo_icon.png
   
flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icons/logo_icon.png"

```
