### ISSUE TITLE
Method not found: 'UnmodifiableUint8ListView'. UnmodifiableUint8ListView(Uint8List(0));

### ISSUE THREAD

**Issue by heitor598** [fluttercommunity/flutter_launcher_icons#593]
### :information_source: Info

I'm using version [flutter_launcher_icons: ^0.14.1](https://pub.dev/packages/flutter_launcher_icons)

### :speech_balloon: Description

When running `dart run flutter_launcher_icons`, I got the following error:

```
Failed to build flutter_launcher_icons:flutter_launcher_icons:

../../../../.pub-cache/hosted/pub.dev/archive-3.4.6/lib/src/bzip2/bzip2.dart:5:7: Error: Method not found: 'UnmodifiableUint8ListView'.
UnmodifiableUint8ListView(Uint8List(0));
```

![Captura de Tela 2024-10-04 às 13 52 25](https://github.com/user-attachments/assets/6b074869-ab73-4a3c-8230-6c2d1b3ac5c6)

### :scroll: Pubspec.yaml

```yaml
dev_dependencies:
  flutter_launcher_icons: ^0.14.1
...
flutter_launcher_icons:
  image_path: "assets/images/ic_ios_launcher.png"
  adaptive_icon_foreground: "assets/images/ic_android_launcher.png"
  adaptive_icon_background: "assets/images/ic_android_launcher.png"
  android: true
  ios: true
```
