### ISSUE TITLE
blank launcher icon on build.

### ISSUE THREAD

**Issue by Sajidpv** [fluttercommunity/flutter_launcher_icons#595]
### :information_source: Info
flutter_launcher_icons: ^0.14.1

### :speech_balloon: Description
when i generate icons it successfully generated icons i can see them in folder . but when i build the app, i got black launcher icons and also when i close and reopen the app, it initially show a blackscreen, then open the app. when i take a release build apk and open the app on real device , device will screenlock automatically ,if i unloack the app will successfully opened and running.

It is working fine with previous version

### :scroll: Pubspec.yaml
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/logos/uracca.png"

  android: "launcher_icon"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"
  # adaptive_icon_monochrome: "assets/icon/monochrome.png"

  ios: true
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  remove_alpha_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true

```yaml
flutter_launcher_icons:
  android: 
  ios: 
  image_path: 
```

**Comment by ning6633** [comment]
I also encountered the same problem, and this is how I solved it。
I hope it can help you


```
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"  # 设置适应图标的背景颜色
  adaptive_icon_foreground: "assets/icon/app_icon.png"  # 设置前景图标（主图标）

```
