### ISSUE TITLE
iOS Dark and Tinted icons are not placed in the correct directory

### ISSUE THREAD

**Issue by vlazdra** [fluttercommunity/flutter_launcher_icons#596]
### :information_source: Info
0.14.1

### :speech_balloon: Description
When running the command it creates an additional folder for the Dark and for the Tinted icons which is not how it's supposed to be. The Dark and Tinted icons should be placed in the already existing or the main AppIcon catalog (taking into account the flavor part if present)

### :scroll: Pubspec.yaml
```yaml
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: 'app_icons/android-development.png'
  image_path_ios: 'app_icons/ios-development.png'
  image_path_ios_dark_transparent: 'app_icons/logo-development.png'
  image_path_ios_tinted_grayscale: 'app_icons/logo-development.png'
  desaturate_tinted_to_grayscale_ios: true
  remove_alpha_ios: true
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'app_icons/logo-development.png'
  adaptive_icon_foreground_inset: 0
  adaptive_icon_monochrome: 'app_icons/logo-development.png'
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
```
