### ISSUE TITLE
In Android I See only a black Circle as icon

### ISSUE THREAD

**Issue by agorji79** [fluttercommunity/flutter_launcher_icons#600]
### :information_source: Info

Flutter 3.24.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5874a72aa4 (8 weeks ago) • 2024-08-20 16:46:00 -0500
Engine • revision c9b9d5780d
Tools • Dart 3.5.1 • DevTools 2.37.2

### :speech_balloon: Description

Hello,

For IOS works every thing with the icon as I expect. But for android I see a black Circle in the Simulator (Pixel_3a_API_34_extension_level_7_arm64_v8a and Medium Phone API 34).

How can I fix it?

### :scroll: flutter_launcher_icons.yaml

```yaml
dev_dependencies:
  flutter_launcher_icons: "^0.14.1"

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon/Ronaldo_icon_1.png"
  image_path_android: "assets/icon/Ronaldo_icon_1.png"
  image_path_ios: "assets/icon/Ronaldo_icon_1.png"

  remove_alpha_ios: true
  background_color_ios: "#ffffff"

  android: "launcher_icon"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"
  # adaptive_icon_monochrome: "assets/icon/monochrome.png"

  ios: true
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true

  web:
    generate: true
    image_path: "assets/icon/Ronaldo_icon_1.png"

    background_color: "#hexcode"
    theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/icon/Ronaldo_icon_1.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/icon/Ronaldo_icon_1.png"


```

### :scroll: Pubspec.yaml

```yaml
name: my_try_1
description: "An App for my son, Sam Gorji"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #flutter pub add material_design_icons_flutter
  flutter_launcher_icons: ^0.14.1
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path_android: "assets/icon/Ronaldo_icon_1.png"
  image_path_ios: "assets/icon/Ronaldo_icon_1.png"
  android: true
  ios: true
  image_path: "assets/icon/Ronaldo_icon_1.png"

```

After installing I see this output:

```shell

$ flutter pub get
dart run flutter_launcher_icons
Resolving dependencies... 
Downloading packages... 
  collection 1.18.0 (1.19.0 available)
  flutter_lints 3.0.2 (5.0.0 available)
  leak_tracker 10.0.5 (10.0.7 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.8 available)
  lints 3.0.0 (5.1.0 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  stack_trace 1.11.1 (1.12.0 available)
  string_scanner 1.2.0 (1.3.0 available)
  test_api 0.7.2 (0.7.3 available)
  vm_service 14.2.5 (14.3.0 available)
Got dependencies!
11 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Building package executable... 
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.14.1)                               
  ════════════════════════════════════════════
  
• Creating default icons Android
• Adding a new Android launcher icon
• Creating mipmap xml file Android
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...              done
Creating Icons for Windows...          done
Creating Icons for MacOS...            done

✓ Successfully generated launcher icons

```

**Comment by shaheer-hybreed** [comment]
Here also same

**Comment by adham-ashraf77** [comment]
Here also same

**Comment by BenSalemOumaima** [comment]
same problem

**Comment by modyflutter** [comment]
same problem flutter 3.24.1 stable

**Comment by modyflutter** [comment]
**problem fixed after downgrade package to 0.13.1
flutter_launcher_icons: ^0.13.1**
my file looks like 
```
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"
``` 

**you need to run** 

```
flutter pub get
dart run flutter_launcher_icons

```

**Comment by Bow-T** [comment]
Same problem

**Comment by Sarvesh223** [comment]
same problem

**Comment by WhistlerChoi** [comment]
If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.

**Comment by DaliaPinto23** [comment]
Same problem using flutter 3.24.3

**Comment by DaliaPinto23** [comment]
> Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.

It solved my problem, than you

**Comment by FahimHoque** [comment]
> Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.

This solved the issue. downgrading to 0.13.1 did not help in my case

**Comment by agorji79** [comment]
> Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.

Thank you @WhistlerChoi! Ii solved the my problem too..

**Comment by rafaelgcs** [comment]
> Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.

I put
`adaptive_icon_background: "#FFFFFF"`
and
`adaptive_icon_foreground: "path/to/icon.png"`

And solved the problem, thank you @WhistlerChoi !

**Comment by daybson** [comment]
> Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.

Didn't work for me. Fails on Android 11, Android 15 but works on Android 7.

Flutter Channel stable, 3.24.3
Dart SDK version: 3.5.3 (stable)

### Pubspec.yaml
name: meuapponto
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

### flutter_launcher_icons.yaml

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"

  android: true

  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

  ios: true

  remove_alpha_channel_ios: true
  background_color_ios: "#ffffff"

  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#3753db"

  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/icon/icon.png"


![image](https://github.com/user-attachments/assets/6dafab74-cebb-4bb7-8d9b-4963c243bb75)

**Comment by Ali-peu** [comment]
> Решено) Если вы объявите adaptive_icon_background, adaptive_icon_foreground, иконки будут созданы как обычно.

Thank you

**Comment by GustavoMartins123** [comment]
G

> > Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.
> 
> Solved. Remember to re-run the package to update the icons/files:
> 
> > dart run flutter_launcher_icons

GOD BLESS YOU, THX.

**Comment by juanhuerta** [comment]
> Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.

Thanks! that worked for me!

**Comment by komiljonovshohjahon** [comment]
> > Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.
> 
> I put in yaml file `adaptive_icon_background: "#FFFFFF"` and `adaptive_icon_foreground: "path/to/icon.png"`
> 
> And solved the problem, thank you @WhistlerChoi !

Solved the issue, thanks

**Comment by kotaroyamazaki** [comment]
same problem

**Comment by kotaroyamazaki** [comment]
> > Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.
> 
> I put in yaml file `adaptive_icon_background: "#FFFFFF"` and `adaptive_icon_foreground: "path/to/icon.png"`
> 
> And solved the problem, thank you @WhistlerChoi !

Thanks. solved

**Comment by YesThatGy** [comment]
> > Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.
> 
> Solved. Remember to re-run the package to update the icons/files:
> 
> > dart run flutter_launcher_icons

This worked for me too. So, the issue that remains is that either: 

1) The documentation needs to be updated to specify that these fields are required on Android, or

2) The package needs to be updated so that these are not required any longer.

**Comment by PierreEhab** [comment]
> > Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.
> 
> I put in yaml file `adaptive_icon_background: "#FFFFFF"` and `adaptive_icon_foreground: "path/to/icon.png"`
> 
> And solved the problem, thank you @WhistlerChoi !

This solved it, but don't forget to "flutter clean" and re run the package with "dart run flutter_launcher_icons"

**Comment by jitendrakohar** [comment]
still , facing the same issue, the icon is totally appearing black: 

`E/AndroidRuntime(13560): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.draw(android.graphics.Canvas)' on a null object reference
E/AndroidRuntime(13560):        at com.android.wm.shell.startingsurface.SplashscreenIconDrawableFactory$AdaptiveForegroundDrawable.draw(go/retraceme 19693c2b0a8439b7183751b64d60893829dbf56dc1e08e0669fc0cfc55754948:6)
E/AndroidRuntime(13560):        at com.android.wm.shell.startingsurface.SplashscreenIconDrawableFactory$ImmobileIconDrawable.preDrawIcon(go/retraceme 19693c2b0a8439b7183751b64d60893829dbf56dc1e08e0669fc0cfc55754948:32)
E/AndroidRuntime(13560):        at com.android.wm.shell.startingsurface.SplashscreenIconDrawableFactory$ImmobileIconDrawable$$ExternalSyntheticLambda0.run(go/retraceme 19693c2b0a8439b7183751b64d60893829dbf56dc1e08e0669fc0cfc55754948:23)
E/AndroidRuntime(13560):        at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(13560):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13560):        at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(13560):        at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(13560):        at android.os.HandlerThread.run(HandlerThread.java:67)
Syncing files to device sdk gphone64 arm64...                      201ms
`
it is generating the icon but when i try to run it showing totally black in color. this is what my pubsec.yaml look likes:
`flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"`

**Comment by shikada10** [comment]
> > Solved) If you declare adaptive_icon_background, adaptive_icon_foreground, the icons will be created as normal.
> 
> Thank you @WhistlerChoi! It solved my problem too..

hey can u show your updated both yaml file 
for some reason its not working for me

this is my file 

```
pubsec.yaml 

flutter_icons:
  image_path: "assets/icon_a.png"
  image_path_android: "assets/icon_a.png"
  #android: "launcher_icon"
  android: true
  ios: true
  
  #min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  
  adaptive_icon_foreground: "assets/icon_a.png"
  
  web:
    generate: true
    image_path: "assets/icon_a.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon_a.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon_a.png"  # Path to your icon image


```
flutter_launcher_icons.yaml
```
flutter_launcher_icons:
  image_path: "assets/icon_a.png"

  image_path_android: "assets/icon_a.png"
  image_path_ios: "assets/icon_a.png"

  android: "launcher_icon"
   #adaptive_icon_background: "#ffffff" # only for Android 8.0 devices and above
   #adaptive_icon_foreground: "assets/icon/icon_foreground.png" # only for Android 8.0 devices and above
  # image_path_android: "assets/icon_a.png"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
   #adaptive_icon_background: "assets/icon_a.png"
   #adaptive_icon_foreground: "assets/icon_a.png"
   #adaptive_icon_monochrome: "assets/icon_a.png"

  ios: true
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true

  web:
    generate: true
    image_path: "assets/icon_a.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/icon_a.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/icon_a.png"

 ```
