### ISSUE TITLE
iOS no dark icon in release mode

### ISSUE THREAD

**Issue by BorisB** [fluttercommunity/flutter_launcher_icons#602]
### :information_source: Info

flutter_launcher_icons: ^0.14.1

### :speech_balloon: Description

I'm using iPhone 12 Pro Max.
In light node all is working fine.
In dark mode:
- On `flutter run` command all is fine, and the icon is displayed correctly.
- On `flutter install` instead of the correct icon, the default one is displayed.
In Xcode build settings, 'App Icon' is set to 'AppIcon' for all profiles.

### :scroll: Pubspec.yaml

```yaml
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "resources/icon.png"
    min_sdk_android: 23 
    remove_alpha_ios: true
    image_path_ios_dark_transparent: "resources/icon-transparent.png"
    adaptive_icon_foreground_inset: 22
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "resources/icon-transparent.png"
```
