### ISSUE TITLE
Could not find package `flutter_launcher_icons`

### ISSUE THREAD

**Issue by Samxury** [fluttercommunity/flutter_launcher_icons#603]
### :information_source: Info

 flutter_launcher_icons: ^0.14.1

### :speech_balloon: Description

whenever I run this command,  
dart run flutter_launcher_icons:generate

it gives me this error
Could not find package `flutter_launcher_icons` or file `flutter_launcher_icons:generate`

### :scroll: Pubspec.yaml

```yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/public_transport.png"
  min_sdk_android: 24  # Minimum Android SDK version
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/public_transport.png"

```
