### ISSUE TITLE
iOS build issue after icon generation

### ISSUE THREAD

**Issue by caporalCoder** [fluttercommunity/flutter_launcher_icons#605]
### :information_source: Info

flutter_launcher_icons: ^0.14.1

### :speech_balloon: Description

This is my flutter version: Flutter 3.24.3 • channel stable.

When I run `flutter run` I am getting the following error after running `dart run flutter_launcher_icons`:
```
Could not build the precompiled application for the device.
Error (Xcode): Target debug_ios_bundle_flutter_assets failed: Exception: Failed to codesign
```

### :scroll: Pubspec.yaml

```yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#2575FC"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
```
