### ISSUE TITLE
app i crashing while launching

### ISSUE THREAD

**Issue by PujaJii** [fluttercommunity/flutter_launcher_icons#609]
### :scroll: Pubspec.yaml

```yaml
flutter_launcher_icons:
  android: 
  ios: 
  image_path: 
```
