### ISSUE TITLE
Getting a black app icon instead of what I declared

### ISSUE THREAD

**Issue by crow-dz** [fluttercommunity/flutter_launcher_icons#610]
### :information_source: Info

flutter_launcher_icons: ^0.14.1

### :speech_balloon: Description

 I am getting a black app icon instead of what I declared but when I removed mipmap-anydpi-v26 folder everything worked , so I am unsure if it is a bug or something else .

3.19.5 Flutter SDK
3.3.3 (Flutter) Dart SDK
emulator API 33

### :scroll: Pubspec.yaml

```yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img3.png"
```
