### ISSUE TITLE
If adaptive_icon_background is NOT a png file, an html colors file is created.

### ISSUE THREAD

**Issue by snoopdoggy322** [fluttercommunity/flutter_launcher_icons#616]
### :information_source: Info

If you need to use, for example, a jpg file for the background of an adaptive icon, an incorrect structure is created, as if a color was written into the config, not a asset file.

### :scroll: Pubspec.yaml

```yaml
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  adaptive_icon_background: "assets/icons/adaptive_icon_bg.jpg"
  adaptive_icon_foreground: "assets/icons/app_icon_fg.jpg"
```
