### ISSUE TITLE
Oddness when generating iOS icon

### ISSUE THREAD

**Issue by 17twenty** [fluttercommunity/flutter_launcher_icons#62]
I've got my pubspec.yml setup as follows:

```
...
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.6.1"

flutter_icons:
  image_path: "assets/logo.png" 
  android: true
  ios: true
  adaptive_icon_background: "#614ec6"
```

I run the command:
```
$ flutter packages pub run flutter_launcher_icons:main
Android minSdkVersion = 16
Creating icons Android
Overwriting default Android launcher icon with new icon
Overwriting default iOS launcher icon with new icon
```

The icon when it installs onto the iPhone however... well.. it has a black border.
<img width="69" alt="screen shot 2018-11-14 at 4 26 48 pm" src="https://user-images.githubusercontent.com/379176/48461922-2e6d8500-e82a-11e8-878f-81fa984470a8.png">

How do I fix that from happening? I used the [studio creator](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=image&foreground.space.trim=0&foreground.space.pad=0.05&foreColor=rgba(0%2C%200%2C%200%2C%200)&backColor=rgb(97%2C%2078%2C%20198)&crop=0&backgroundShape=square&effects=none&name=ic_launcher) to generate it.

This is the original image:
![ic_launcher](https://user-images.githubusercontent.com/379176/48461974-61b01400-e82a-11e8-9c8c-12074a6483b2.png)
