### ISSUE TITLE
Apk fails on running flutter_launcher_icons

### ISSUE THREAD

**Issue by lijuj2** [fluttercommunity/flutter_launcher_icons#621]
### :scroll: Pubspec.yaml

```yaml
flutter_launcher_icons:
  android: 
  ios: 
  image_path: 
```

**Comment by lijuj2** [comment]
May be after the new update, Please check it. Apk works find if not using flutter_launcher_icons.

**Comment by snapsl** [comment]
@lijuj2 could you please add more context to this issue?
@MarkOSullivan94 The creation of launcher icon seems to be broken with the latest flutter 3.27 release, specifically for android. I have not tested whether other platforms are also affected.

**Comment by lijuj2** [comment]
after adding flutter launcher icons, the released apk not runs on android.

**Comment by belabiedredouane** [comment]
> after adding the flutter launcher icon the icon becomes black and app runs abnormally if automatically closes for that what to do

please visit this https://github.com/fluttercommunity/flutter_launcher_icons/issues/618#issuecomment-2526372765 
may be it helps

**Comment by lijuj2** [comment]
Thank you very much. Let me try.

**Comment by baixiongmao** [comment]
```yaml
flutter_launcher_icons: ^0.14.2
```

```yaml
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"
  adaptive_icon_background: "#FF0000" 
  adaptive_icon_foreground: "assets/logo/logo.png"
```
```shell
flutter clean
flutter pub get
dart run flutter_launcher_icons
```
success!
