### ISSUE TITLE
Make a file that makes null error

### ISSUE THREAD

**Issue by ethanmorian** [fluttercommunity/flutter_launcher_icons#623]
### :information_source: Info

```yaml
name: flutter_hawkeye
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
```

### :speech_balloon: Description

I use my phone to run app. when install is done, app icon is just black and when i touch to run screen change to lock screen. after I unlock the screen success to run app. so screen transfer to lock screen when i touch or hover the app icon and i find out in stack overflow someone's comment to how to fix it. It is delete a file in \android\app\src\main\res\mipmap-anydpi-v26. after that it is working properly. I think it makes null error

### :scroll: Pubspec.yaml

```yaml
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/image/app_icon.png"

  android: "launcher_icon"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"
  # adaptive_icon_monochrome: "assets/icon/monochrome.png"

  ios: true
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true
```
