### ISSUE TITLE
Running this breaks my Xcode Runner!

### ISSUE THREAD

**Issue by P-Jay357** [fluttercommunity/flutter_launcher_icons#634]
### :information_source: Info

Running the command updates incorrect parameter, which breaks Xcode.

### :speech_balloon: Description

It generates the files fine, but for some reason it also updates the `ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS` values in project.pbxproj to be `AppIcon-staging`, when it's originally just set to `YES`.

This then breaks the Xcode project and the change ahs to be reverted.

It works fine on Android though!

### :scroll: Pubspec.yaml

Staging:
```yaml
flutter_launcher_icons:
  image_path: "assets/images/app_icons/staging.png"

  android: true
  min_sdk_android: 21 # android min sdk min:16, default 21

  ios: true
  remove_alpha_ios: true
```
Prod:
```yaml
flutter_launcher_icons:
  image_path: "assets/images/app_icons/production.png"

  android: true
  min_sdk_android: 21 # android min sdk min:16, default 21

  ios: true
  remove_alpha_ios: true
```
