### ISSUE TITLE
iOS icon generation fails when using custom xcodeproj name

### ISSUE THREAD

**Issue by jierlausson** [fluttercommunity/flutter_launcher_icons#637]
## Description
When using a custom xcodeproj name (different from the default "Runner.xcodeproj"), the tool successfully generates the icons but fails with a PathNotFoundException while trying to update the project file.

## Steps to Reproduce
1. Have a Flutter project with a custom xcodeproj name (e.g., "MyApp.xcodeproj")
2. Configure `flutter_launcher_icons` in yaml file with the custom xcodeproj path:

```yaml
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher_hml.png"
  remove_alpha_ios: true
  xcodeproj_path: "ios/MyApp.xcodeproj"
```

3. Run the command:
```bash
dart run flutter_launcher_icons -f launch_icons_hml.yaml
```

## Current Behavior
The tool generates the icons correctly in the Assets.xcassets folder but throws an error:

```
✓ Successfully generated launcher icons
Unhandled exception:
PathNotFoundException: Cannot open file, path = 'ios/Runner.xcodeproj/project.pbxproj' (OS Error: No such file or directory, errno = 2)
```

## Expected Behavior
The tool should use the provided `xcodeproj_path` when trying to update the project file instead of always looking for "Runner.xcodeproj".

## Environment
- Flutter version: 3.19.0
- flutter_launcher_icons version: 0.14.3
- Operating System: macOS Sonoma 14.3.1

## Additional Context
Even though the error occurs, the icons are correctly generated in the proper location. The issue seems to be only with the project file update step.
