### ISSUE TITLE
Does not generate mac icons when using flavors

### ISSUE THREAD

**Issue by kjxbyz** [fluttercommunity/flutter_launcher_icons#638]
### :information_source: Info

```
flutter: ^3.29.2
flutter_launcher_icons: ^0.14.3
```

### :speech_balloon: Description

Does not generate the macOS icons when using flavors

### :scroll: Pubspec.yaml

`flutter_launcher_icons-pro.yaml`
```yaml
flutter_launcher_icons:
  android: true
  image_path: "launcher/android-free.png"
  image_path_ios: "launcher/ios-pro.png"
  macos:
    generate: true
    image_path: "launcher/mac-pro.png"
  web:
    generate: false
  windows:
    generate: false
```
