### ISSUE TITLE
Error creating adaptative icons

### ISSUE THREAD

**Issue by gturmo** [fluttercommunity/flutter_launcher_icons#641]
### :information_source: Info
 0.14.3

### :speech_balloon: Description
 During execution of dart run flutter_launcher_icons I get ✗ ERROR: InvalidConfigException 
Missing "image_path" or "image_path_android" + "image_path_ios" within configuration The problem is that if I write an image_path with an icon, it doesn't creates adaptative android icons.

### :scroll: Pubspec.yaml

```yaml
flutter_launcher_icons:
  android: true
  ios: true
  image_path: null
  image_path_android: null
  image_path_ios: "assets/icon_ios_no_alpha.png"
  android_adaptive_icon_foreground: "assets/icon_foreground.png"
  android_adaptive_icon_background: "assets/icon_background.png"
```
