### ISSUE TITLE
IOS App crashes with Dart v3.6.2

### ISSUE THREAD

**Issue by kiwicmc** [fluttercommunity/flutter_launcher_icons#645]
### :information_source: Info
0.14.3

```
[!] Flutter (Channel stable, 3.27.4, on macOS 15.4.1 24E263 darwin-arm64, locale en-NZ)
    • Flutter version 3.27.4 on channel stable at /Users/chris/fvm/versions/3.27.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d8a9f9a52e (3 months ago), 2025-01-31 16:07:18 -0500
    • Engine revision 82bd5b7209
    • Dart version 3.6.2
    • DevTools version 2.40.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```

### :speech_balloon: Description
Error (Xcode): ../../flutter/packages/flutter/lib/src/dart_plugin_registrant.dart:1:1: Error: The specified language version is too high. The highest supported language version is 3.6

### :scroll: Pubspec.yaml

```yaml
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon/icon.png"

  ios: true
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true

```
