### ISSUE TITLE
Add a warning, if a user trys to add a icon with alpha channel as ios icon. Because this is not allowed by Appstore

### ISSUE THREAD

**Issue by HerrNiklasRaab** [fluttercommunity/flutter_launcher_icons#67]

**Comment by lifetin** [comment]
最好能自动去掉alpha通道

**Comment by mockturtl** [comment]
Quick workaround: https://stackoverflow.com/a/26177376

**Comment by zmeggyesi** [comment]
A +1 on @sma 's suggestion. Google Play requires a 32-bit PNG (_with_ transparency), while the App Store specifically _disallows_ an alpha channel.

I would be great if the tool could account for this and strip the alpha from the iOS icons.

**Comment by douglasrosa0110** [comment]
@zmeggyesi you can use the params to resolve the alpha problem:

**pubspec.yaml**
```
flutter_icons:
  # image_path: "assets/images/favicon.png"
  image_path_android: "assets/images/favicon.png"
  image_path_ios: "assets/images/favicon_ios.png"
```
