### ISSUE TITLE
The icon shown remains the default one provided by Flutter

### ISSUE THREAD

**Issue by omrllm** [fluttercommunity/flutter_launcher_icons#77]
Hi guys,

I've followed the main guide to use this package, but the default Flutter icon still shows up.. and I don't understand why.

Here is the repo of the app where I get this [problem](https://github.com/agetsy/getsy).

Minimal pubspec.yaml: 
```
dev_dependencies:
  flutter_test:
    sdk: flutter

  # launcher icons
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
```

the full path of icon.png is: `mymainrepo/assets/icon/icon.png`

Flutter version: 1.0 **beta channel**
<br/>
Anything else I need to provide?
