### ISSUE TITLE
Adaptive icons solid color background not working

### ISSUE THREAD

**Issue by talamaska** [fluttercommunity/flutter_launcher_icons#79]
```
flutter_icons:
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#EA7819"
  android: true
  ios: false
```
the icon still has white background around it
ran couple of times flutter packages pub run flutter_launcher_icons:main
icons are not regenerated
