### ISSUE TITLE
A dependency may only have one source error

### ISSUE THREAD

**Issue by NTMS2017** [fluttercommunity/flutter_launcher_icons#86]
I am getting an error while trying to use the plugin. Any idea?

**I have project folder as shown below**
	- Project Folder
	- Android
	- iOS
	- assets
		- images
			- logo
				- LogoLoading.png
				- LogoIOS.png
	- lib
**And my configuration like shown below.**

flutter_icons:
  image_path_android: "assets/images/logo/LogoLoading.png"
  image_path_ios: "assets/images/logo/LogoIOS.png"
  android: true
  ios: true

**Error:**

/Users/niyazitoros/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in capital_cep...                
Error on line 60, column 5 of pubspec.yaml: A dependency may only have one source.
    image_path_android: "assets/images/logo/LogoLoading.png"

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pub get failed (65)
Process finished with exit code 65

**Comment by MarkOSullivan94** [comment]
Can you paste exactly what your yaml config looks like with correct indentation. The config requires indentation to be correct otherwise you will get errors.

**Comment by NTMS2017** [comment]
thanks Mark, indentation was okay. I cannot put the indentation here but here is how it was.

```
    flutter_icons:
        image_path_android: "assets/images/logo/LogoLoading.png"
        image_path_ios: "assets/images/logo/LogoIOS.png"
        android: true
        ios: true
```
