### ISSUE TITLE
Icon launch install error

### ISSUE THREAD

**Issue by jitheshkramesh** [fluttercommunity/flutter_launcher_icons#89]
Error on line 46, column 12 of pubspec.yaml: Invalid version constraint: Could not parse version "launcher_icon". Unknown text at "launcher_icon".
  android: "launcher_icon"
           ^^^^^^^^^^^^^^^

**Comment by andim27** [comment]
+

**Comment by ayinloya** [comment]
Were you able to resolve this issue?

**Comment by vtisnado** [comment]
This just happened to me and I found that the indentation was wrong. Just check the "flutter_icons:" text doesn't have any space before, the three lines bellow should start with 2 spaces:

```
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icono.png"

```
