### ISSUE TITLE
Error on generation "pub finished with exit code 2"

### ISSUE THREAD

**Issue by YAPPDEF** [fluttercommunity/flutter_launcher_icons#94]
Not working anymore (^0.7.0)

```
flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/icon.png"
```

```
my-project: flutter packages get
Running "flutter packages get" in my-project...                    0.7s
my-project: flutter packages pub run flutter_launcher_icons:main
Android minSdkVersion = 
FormatException: Invalid number (at character 1)

^

pub finished with exit code 2
```
