### ISSUE TITLE
app icon color was different while i generate icons 

### ISSUE THREAD

**Issue by pmrajani** [fluttercommunity/flutter_launcher_icons#98]
Here is my code:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"

**It is generating slightly different color instead of my actual logo for app.**

**Comment by inceptusp** [comment]
I am having the same issue, look the attached files...
Original: ![Original](https://user-images.githubusercontent.com/17789155/57504004-118da800-72c9-11e9-8014-b2343e6cd8bd.png)
 Generated: ![Generated](https://user-images.githubusercontent.com/17789155/57504005-12263e80-72c9-11e9-937a-8c0b9959c808.png)

**Comment by pmrajani** [comment]
Yes same with me. 
Admin can you please look at this?

**Comment by skybur** [comment]
It seems this is caused by an update to the `image` dependency. After I changed the `image` package version to 2.0.7 my icon color is correct.
You can change it by navigating to this package folder in pub_cache

**Comment by Inovactio** [comment]
I am having the same issue and change the image package version to 2.0.7 doesn't work

**Comment by HelgeSverre** [comment]
Having the same issue, the original color is 
#EB6F93
The generated color is: #936FEB

**Comment by skybur** [comment]
@Inovactio you need to force the version to 2.0.7.
This is the current pubspec for this package
```
dependencies: 
image: "^2.0.0"
```
You need to change ` "^2.0.0"` to `"2.0.7"

@HelgeSverre yup that's because the `image` package updated the position of ARGB.
From the version 2.0.8. changelog
```
- Use #AARRGGBB for colors instead of ##AABBGGRR, to be compatible with Flutter image class.
```

**Comment by HelgeSverre** [comment]
Thanks for the quick fix @skybur, that fixed the issue for now.

**Comment by mykdavies** [comment]
Thanks @skybur, perfect timing as I just hit this too!

To be explicit for anyone else following this, I edited  ~/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/pubspec.yaml to read:
`dependencies:
  image: "2.0.7" #<--- No "^"! Specific version only!
  args: "^1.5.0"
 `
and did a `flutter packages get`
then ran `flutter packages pub run flutter_launcher_icons:main` again.

**Comment by HelgeSverre** [comment]
You can also just set the specific version in your ```pubspec.yaml``` file, like so:
```
dev_dependencies:
  image: 2.0.7 # <- Put this here
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Tjommi_app-icon.png"
  adaptive_icon_background: "#EB6F93"


```

**Comment by mykdavies** [comment]
Thanks @HelgeSverre, that's a bit neater!

**Comment by scarings** [comment]
> You can also just set the specific version in your `pubspec.yaml` file, like so:
> 
> ```
> dev_dependencies:
>   image: 2.0.7 # <- Put this here
>   flutter_launcher_icons: "^0.7.0"
>   flutter_test:
>     sdk: flutter
> 
> flutter_icons:
>   android: true
>   ios: true
>   image_path: "assets/icon/app-icon.png"
>   adaptive_icon_background: "#EB6F93"
> ```

Same issue, not working for me :(
```
image: "^2.0.7"
flutter_launcher_icons: ^0.7.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

```
